### PR TITLE
[TS] LPS-83271

### PR DESCRIPTION
**Pull request by yuhai**
Hi @matethurzo 

The root issue is that temp file doesn't been closed if export failed because the code (https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/zip/ZipWriterImpl.java#L126) didn't execute.

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61247. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/fd81c38abde0~5...fd81c38abde0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61248. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e702db48b2e2~5...e702db48b2e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61252. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e702db48b2e2~5...e702db48b2e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61257. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/68761f0d8068~5...68761f0d8068) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61262. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/ecac3319c7ac~5...ecac3319c7ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
