### PR TITLE
LPS-78137 fix unaligned user portrait and process title in listview

### PR DESCRIPTION
**Pull request by palius**

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by peterborkuti** [comment]
Does not seem to me related. First is with Form second is something with Search.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55598. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/cb9e0b64f954~1...cb9e0b64f954) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55627. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e8485d269694~1...e8485d269694) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
