### PR TITLE
pr-1367

### PR DESCRIPTION
**Pull request by kmaria**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kmaria** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35955. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e3c245e~3...e3c245e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
