### PR TITLE
[TECHNICAL-SUPPORT] LPS-57007

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Mate,

Due to the issue is from EE customer, and our cse wants to take the pull reuqest as high priority.
Could you please give this priority and review?

Regards,
Hai

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @yuhai,

I've checked the pull request, but I'm not sure how can this be possible.

If the message listeners runs on the staging site, it will change the status for the article. When this article is being published it will be published with the expired state so it should be the same on live.

The question is when and what changes the state of the article? Is it exported with the wrong state or is it being imported with the wrong state?

Also I've seen a mistake in the ticket, can you please clarify it? The ticket say this has been reproduced with local staging, but then the ticket mention this: >Navigate to Admin--> Content --> Web Content in "Live Site"< I assume this means navigating to the live site on the control panel. However you cannot do it, the control panel always shows the stage site. So probably the observed behavior is wrong?

Thanks,

Máté

**Comment by yuhai** [comment]
Hi Mate,

**For the "Navigate to Admin--> Content --> Web Content in "Live Site""**
Sorry, I do one mistake. In LPP ticket, the customer enable remote staging. If we enable remote staging, we will see the behavior.

**If the message listeners runs on the staging site, it will change the status for the article. When this article is being published it will be published with the expired state so it should be the same on live.**

Yes, however, the issue occurs in when expirationDate < publishDate(now date) and this article's status is not expired. That is to say, when schedule listener doesn't work yet, we execute "publish to live" or "export". At this time,  expirationDate < publishDate(now date), the article should be expired state. If we never execute "publish to live" when the article of staging site expired (after our listener changes the state), the article of live site won't be expired because its expirationDate is null. Or we don't enable staging, and execute the export the article and import the article, and the issue also should occur.

The wrong state occurs in the process of import. The article's state is approved and expirationDate < importDate(now date). Actually, the article has been expired. But before listener works, we execute the export operation (at this time, expirationDate <nowDate) and the article's state is approved.

Please also refer to the fix explanation from https://issues.liferay.com/browse/LPS-57007?focusedCommentId=638985&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-638985

Regards,
Hai

**Comment by yuhai** [comment]
Hi Máté,

Hope you are doing well.

When you have free time, could you please check my previous explanation regarding the issue? If you have other concerns, please kindly let me know.

Regards,
Hai

**Comment by matethurzo** [comment]
Hey,

Sorry for the delay, thank you for the explanation, I only have one question left. So the listener is running on the stage site, but is it running on the live site? I think the reason that the status was not changed during the export/import process is because the listener will run on the live site, according to the schedule and it will change the article.

Thanks!

**Comment by yuhai** [comment]
Hi Máté,

According to JournalArticleLocalServiceImpl.checkArticlesByExpirationDate(), the listener should be running in stage and live site. But for the case, due to import process will change the article's expirationDate for null. That is to say, in live site, due to expirationDate is null, it will be treated as never  expired. So even though when the listener runs in live site, it won't make change for those articles which their expirationDate is null.

Regards,
Hai

**Comment by yuhai** [comment]
Hi Máté,

Is there any updates?

Regards,
Hai

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28614. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
