### PR TITLE
[TECHNICAL-SUPPORT] LPS-66895

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-66895

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

Do you have any update about this pull request?

Thank you

**Comment by jorgediaz-lr** [comment]
@matethurzo I have rebased my changes to today master

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@jorgediaz-lr the group is returning true on purpose and we leverage that logic at several places, changing that would definitely cause regression bugs.

on the other hand the UI is still relying on that logic, so even though the typesettings doesn't have the blog in it, the UI should show that the blog is turned on and other logic should use the live group id.

I think maybe the wrong groupId is passed somewhere?

Is the UI showing turned on for blogs? Then I think this logic in GroupImpl is fine, the problem will be around where the group id is being used

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo,

After some investigations and comparing master and 6.2.x branchs, I have detected that https://issues.liferay.com/browse/LPS-64880 changed the behavior:
  - Before that LPS, the portlets with missing entry in group.typesettings retrieves check info from **isPublishToLiveByDefault()**
  - After that LPS (only in master), the portlets with missing entry in group.typesettings retrieves check info from **stagingGroup.isStagedPortlet**

But that method always return true.

For me it doesn't makes sense that before activating staging we are getting **isPublishToLiveByDefault** info from portlet, but after activating staging, all new portlets will have always staging activated , even if  **isPublishToLiveByDefault = false** in data handler.

**Comment by matethurzo** [comment]
Hey @jorgediaz-lr 

I'm getting a bit confused now, I'm not sure if we have a bug after all.

The first item you wrote seems to be wrong so I think it was a valid change to fix that.
The second point also seems to be okay for me, as I wrote previously this is a valid logic, we have been relying on that at every place that method is being called.

Basically if you activate staging even if that information is coming from the isPublishToLiveByDefault there has to be an entry in the typeSettings. After that, the isStagedPortlet method will return that value. So if the isPublishToLiveByDefault was false and you turn staging on you'll have a false value in the typeSettings and the isStagedPortlet will return false.

After all it's a rule that if there is no information about the portlet in the type settings, it is treated as enabled for staging. If the typeSettings has nothing about blogs in it, it means the blogs is turned on, and the entry should be created in the staging group.

If the blogs is missing from typeSettings, my question is how is it missing? No one should modify the DB records directly, so that's not a viable option.
If the staging is turned on normally an false entry should be written to the typeSettings.

Also the typeSettings values should be upgraded properly for the new portlet Ids, so that cannot be a problem as well.

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

About "If the blogs is missing from typeSettings, my question is how is it missing?" is caused during upgrade:
In Liferay 6.0 we are storing portletId=33 but in 6.1 and 6.2 we are storing portletId=161 (both portletsId belong to blogs)

About "it's a rule that if there is no information about the portlet in the type settings, it is treated as enabled for staging"
In case you have Staging Local activated and you are installing a new portlet (for example Audience Targeting) does it makes sense to ignore *isPublishToLiveByDefault* and always having staging activated for new installed portlets?

**Comment by matethurzo** [comment]
Hey @jorgediaz-lr 

The first part is an upgrade issue, can be easily fixed, but during the upgrade the portlet id for blogs is getting deleted? Anyhow this is an upgrade issue needs to be fixed for sure.

The Audience targeting had a bugfix for that scenario: https://issues.liferay.com/browse/WCM-534 they are doing their special logic to decide where to put the newly created entities.

the isPublishToLiveByDefault actually should not control the configuration of the portlet for a staged site, but actually it should control whether a portlet should be selected to be published by default when you are on a publish screen. It's an old piece of code maybe it's obsolete already.

Regarding this pull, I'm closing it, as it seems to be an upgrade problem.

Thank you!

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Thank you for the information, About LPS-66895, I am going to review the upgrade process.

I am also going to backport https://issues.liferay.com/browse/LPS-64880 as it is reproduced in 6.2.x

One final question: during my testing I detected a NPE in *isStagedPortlet* in case of having a uninstalled portlet. That NPE stops 'for' iterations and we return true.
I included the solution in my pull: https://github.com/matethurzo/liferay-portal/pull/1503/commits/3179c536422fa137ec159485411def603878d350
```
 				Portlet stagedPortlet = PortletLocalServiceUtil.getPortletById(stagedPortletId);
+				if (stagedPortlet == null) {
+					continue;
+				}
```
This NPE is only reproduced in case of having in typesettings a uninstalled portlet and after it another one with staging=false

Do you want me to send that minor fix in other LPS?

Thank you

**Comment by jorgediaz-lr** [comment]
About my last comment, I have sent NPE fix in LPS-67338, see: https://github.com/matethurzo/liferay-portal/pull/1510

**Pull request closed without merging**
