### PR TITLE
LPS-54100

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @zxdgoal,

I've checked this pull request, but I think this is not a proper solution. It seems like this is fixing the symptom not the root cause.

The reason we are getting that null pointer is that we are looking for that element but for some reason it's not there. I think we have added the image to the LAR file in a wrong way, because there is an XML element telling the framework that the LAR should contain an image, but for some reason it's not there.

Can you please check why it is not there? Is that referenced image is properly exported?

Thanks!

Máté

**Comment by zxdgoal** [comment]
Yup, will resend.

**Comment by matethurzo** [comment]
Thank you!

**Pull request closed without merging**
