### PR TITLE
LPS-83628 SiteNavigationMenuPDH - createMissingNavigationMenu to sites created from template

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/196. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2c2ebb5494e8~1...2c2ebb5494e8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
