### PR TITLE
LPS-81816 Publication on "fake" remote live fails due to a database lock as a result of export/import running in the same transaction

### PR DESCRIPTION
**Pull request by giros**
Please see the background information section on the ticket https://issues.liferay.com/browse/LPS-81816

Note: The mass delete method can be affected by ORA-01795 on Oracle database when there are more than 1000 changeset entries. A general solution for this is currently being developed in https://issues.liferay.com/browse/LPS-82215 so I kept using the DynamicQuery here.

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by giros** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60580. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a3fb5610597f~1...a3fb5610597f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
