### PR TITLE
LPS-55995

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @zxdgoal 

I've reviewed the pull request, but I think this is not the right solution. The problem seems to be the user is not being listed after turning staging on, but since the user is not related to any groups, so by changing the group on the JSP to the live group should have no effect.

Since this seems to solve the issue I assume the problem is somewhere else, because these are unrelated.

During the publication the teams are being published, so that shouldn't be the problem. Also since they are published it is unnecessary to change the group to the live one.

I think the problem can be that the UserLocalServiceImpl.search method filters the user out for some reason. I think we might want to fix that, and it should be ok.

Can you please check the query if that is true?

Thanks,

Máté

**Comment by zxdgoal** [comment]
Hey Mate

Ok. You meant the search method should return the user regardless of the group ID?

I will figure out the reason. 

Thanks
John

**Comment by matethurzo** [comment]
Hey,

The user entity itself has nothing to do with the group that's what I meant. It it related to the group in the sense of it can be assigned to groups.

The reason I think the problem is not the group id is that if I create a site, enable staging on it, and then I assign the user to the site and I try to assign this user to a team, the user is not listed in this scenario too. 
In this case the team is related to the staging site but still the user is not showing up.

The other reason this fix is probably not good is that the team is being published too, so I think the proper solution is to publish these assignments too if that's possible.

Thanks,

Máté

**Comment by zxdgoal** [comment]
Hey Mate

> so I think the proper solution is to publish these assignments too if that's possible.

I agree with this. But right now it seems that we do not have this logic.

This is how it works right now:

>if I create a site, enable staging on it, and then I assign the user to the site and I try to assign this user to a team, the user is not listed in this scenario too. 
In this case the team is related to the staging site but still the user is not showing up.

In this case, the user is still assigned to the Live group because of this code in site-memberships-web/src/META-INF/resources/view.jsp
```
Group group = GroupLocalServiceUtil.getGroup(groupId);

if (group != null) {
	group = StagingUtil.getLiveGroup(group.getGroupId());
}

...
portletURL.setParameter("groupId", String.valueOf(group.getGroupId()));
```
Please refer to https://issues.liferay.com/browse/LPS-23015.

So the user is indeed associated to Live site, rather than staging site and you won't get the user as the search method filter the result with Staging site group id.

I can see this code could cause a bug:
1.turn on local staging for a site.
2.assign a user to this site.
3.turn off staging without publication.
4.The user should NOT be assigned to the live site as we do no publish.
However the user is indeed assigned to the live site.

I think you should these issues with keeping assignment for staging site while staging is on. And then publish this relationship to live site when publication.

Do you agree with this?

Thanks
John.

**Comment by matethurzo** [comment]
Hey,

So when staging is turned on and you create a site team in a staged environment the site team will be assigned to the staging group instead of the live group. And the Site Team is being created on the live site during the publication too, check PermissionImporter:71 until PermissionImporter:86.

Even with your solution it's a bug, since even if we assign the users to the live site, the site team can be assigned to the staging group which makes it inconsistent.

Have you checked your solution for the scenario if the first step is turning on staging?

**Comment by zxdgoal** [comment]
hey mate 

If the first step is turning on local staging, even if we assign a user to a team created under staging model, when we publish and turn off staging, there is not any team in the site. 

So even if without my fix , creating a team in staging model , and this team will not be published to live though there were indeed two team in the table.

**Comment by zxdgoal** [comment]
The customer stuck at this issue as they can see the user with remote staging on; but cannot with local staging on  

They believe this inconsistency is an issue

**Comment by matethurzo** [comment]
Hey John,

(1) Yes this is an issue, that's certain I'm not questioning that.
(2) The user is independent from the group, but a we know we can assign users to groups. Please check the following scenario:
(a) turn staging on, assign a user to the site. Check if the user is assigned to the stage group or the live group.
(b) assign a user to the site. turn staging on. Check if the user is assigned to the stage group or the live group.
(3) The teams are being published under certain conditions, so we need to evaluate if the association between the group/team and the user should be published or not.

**Comment by zxdgoal** [comment]
a) Live group. The reason is the code I mentioned.  This is expected ?
b) In this case, I found only the default user(omni admin) has relationships with both live and staging site.  The new created user only has relationship with staging site
c) it is weird that any midification to a staged team will not be published to the live one any way in my testing

I hope my memory is good enough as I have no laptop at hand. 

I still think the code mentioned is responsible. 

If the user only assigned the live group, we can not search it out without using live group id.

**Comment by hhuijser** [comment]
Hey @matethurzo 

Would you have time today to look at John's comment and help getting to a good solution for this one?
It's a customer issue, so it's kind of urgent,

Thanks!

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27138. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey,

I've decided to push this forward to not hold off the customer from getting a fix, I'm going to investigate some more, and push additional changes if necessary.

Thanks for the investigation @zxdgoal!

Máté

**Comment by zxdgoal** [comment]
Many thanks, Mate

I will help investigating as well.

**Pull request closed without merging**
