### PR TITLE
LPS-60734

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @yuhai before we move on with this change, I'd like to know more about the environment. The ticket only mentions that the default locale is different, but remote staging works the following way: all the languages set up in the stage site, has to be also present on the remote live site. The ticket does not hold any information on this. Can you please clarify the exact language settings of both the sites before we move forward?

**Comment by yuhai** [comment]
Hi Mate,

I  am sorry I don't update the fix explanation in LPS. Please refer to the below explanation:

The root issue is that we don't set SiteDefaultLocale in the import process in remote staging.

In local Staging: please refer to the below logic:
ParallelDestination.run() {populateThreadLocalsFromMessage(message); //**finish the setSiteDefaultLocale**}->BaseMessageListener.receive()->..->LayoutStagingBackgroundTaskExecutor.execute()->LayoutStagingBackgroundTaskExecutor.call()-ExportImportLocalServiceUtil.importLayouts()
This is the same thread so the issue won't occur.

In remote staging, we should set SiteDefaultLocale otherwise LocaleUtil.getSiteDefault()=null in the whole import progress. This will cause some issues. For example, **on master, for prepareLocalizedFieldsForImport(Locale defaultImportLocale) in AssetVocabularyModelImpl , it will change default-local wrong and cause import wrong local as default-local.**

Please refer to the below logic to check why it doesn't set.

ParallelDestination.run()->BaseMessageListener.receive()>
LayoutRemoteStagingBackgroundTaskExecutor.execute() {StagingServiceHttp.publishStagingRequest()//133 line}->StagingServiceHttp.publishStagingRequest(){}

From my understanding, this method will invoke StagingServiceUtil.StagingServiceUtil()("remote site" will import the exported lar). In this process, we don't execute LocaleThreadLocal.setDefaultLocale() because the import process was invoke by http request(execute from another server). This is different from local staging.

For the origin issue in ee-6.2.x, please refer to AssetVocabularyStagedModelDataHandler.doImportStagedModel()->getVocabularyTitleMap(), we use titleMap.put(PortalUtil.getSiteDefaultLocale(groupId), name); When execute addVocabulary(), we use "String name = titleMap.get(LocaleUtil.getSiteDefault());" Due to LocaleUtil.getSiteDefault() can't get real siteDefaultLocal (we set it in PortalUtil.getSiteDefaultLocale(groupId)), this name will empty. And LPS-60734 reported error will occur.

Thanks,
Hai

**Comment by yuhai** [comment]
Hi Máté,

The issue came from EE customer. Is it possible that you can review this with a higher priority?

Best Regards,
Hai

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32764. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
