### PR TITLE
[TECHNICAL-SUPPORT] LPS-83795

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @moltam89

> Relevant tickets:
> 
> https://issues.liferay.com/browse/LPP-30959
> https://issues.liferay.com/browse/LPS-83795
> 
> If Staging is configured for a site but it is disabled for a specific portlet in the configuration (like Web Content or Calendar), having an Asset Publisher can still cause the portlet data to be staged as if it were enabled. This is because the Asset Publisher itself is exporting all references without checking for whether Staging is enabled for each specific type of asset entry.
> 
> I think the expected behavior is, for any type of content, whenever Staging for it is disabled in the configuration, that means it should not be published over, and the staging and live sites treated separately (in the case of local Staging, it can do the fancy direct live modification from the Staging site for that type of content, and otherwise the two treated totally independently). It's my understanding the presence of an Asset Publisher should not be a factor in this behavior.
> 
> With this change, if a portlet (like Calendar) can be staged but has Staging disabled, and an Asset Publisher references that portlet's content, then:
> 
> - With local Staging, the Staging site does not have the content, so the Asset Publisher does not display it. Instead the relevant portlet directly modifies the live site (which matches the expected pattern for non-staged content; it should be modified directly on the live site instead), and only the live site has the originally present content.
> - With remote Staging, the remote (live) site does not get the portlet data either (after a publish), though more can be added to either independently.
> - In both cases, the portlet's content is never published because it was not configured.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61705. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/ff0ae44c1d4a~1...ff0ae44c1d4a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61711. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/b6e606bed7cb~1...b6e606bed7cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Alec-Shay** [comment]
Thanks!

**Pull request closed without merging**
