### PR TITLE
LPS-74828 Button for changing between public and private pages is not working for export templates

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Máté,

This is the same fix as was for LPS-74463.
I think, that we should create a common module for staging and exporting to avoid code duplication.
Do you think, that we can make an LPS for this task?

Thank you in advance
Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:reopen

**Comment by peterborkuti** [comment]
I have to change the hidden field name because of POSHI tests rely on searching for 'Name'

**Comment by peterborkuti** [comment]
In the meantime POSHI was somewhat fixed, so this LPS is OK

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52111. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52135. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
