### PR TITLE
[TECHNICAL SUPPORT] LPS-88482 Add dependency to DDM API module.

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi @matethurzo,

I'm resending this fix as you asked me on https://github.com/matethurzo/liferay-portal/pull/2333#issuecomment-448129604.

Thanks in advance for your review!

https://issues.liferay.com/browse/LPS-88482

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/273. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
