### PR TITLE
[TECHNICAL SUPPORT] LPS-88482 Add dependency to DDM API module.

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi @matethurzo,

Can you please review it? I'm sending this solution to master, but I need to backport it to 7.1.x ASAP.

Thanks in advance.

https://issues.liferay.com/browse/LPS-88482

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
hey @natocesarrego the change is breaking staging tests. please check what could be the problem and resend

**Comment by natocesarrego** [comment]
Thanks for your feedback, @matethurzo. I'm looking at these failures right now.

**Pull request closed without merging**
