### PR TITLE
LPS-66757 Do not import global custom field information on site template propagation

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by matethurzo** [comment]
hey @epgarcia I was on vacation, but I'll check this pull soon.

**Comment by epgarcia** [comment]
:+1: Thanks!

**Comment by epgarcia** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@matethurzo could you please have a look at this pull? thanks!

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42407. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Thank you! 👍

**Comment by matethurzo** [comment]
@juliocamarero @epgarcia no problem, sorry for taking so long

**Pull request closed without merging**
