### PR TITLE
Lps 90127 91442

### PR DESCRIPTION
**Pull request by balazssk**
Hi @matethurzo ,

Can you please review?

https://issues.liferay.com/browse/LPS-90127
https://issues.liferay.com/browse/LPS-91442

Thanks,

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @matethurzo ,
Can you please have a look at this PR?
Thanks,

**Comment by matethurzo** [comment]
in progress

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
need to verify if the staging suite is green

**Comment by matethurzo** [comment]
@balazssk can you please verify if the failures are related?

**Comment by balazssk** [comment]
checking

**Comment by balazssk** [comment]
Hi @matethurzo ,
I've started the test suite on the master branch without my modifications and found that all the above problems are present there as well:
https://github.com/balazssk/liferay-portal/pull/5#issuecomment-474455173

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70145. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
