### PR TITLE
[TECHNICAL SUPPORT] LPS-88254 Log trace should be WARN level

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-88254

We are having several issues during asset publisher export/import (related to [LPS-82958](https://issues.liferay.com/browse/LPS-82958)) and I think we should change AssetPublisherExportImportPortletPreferencesProcessor trace from debug to warn in order to ease customer diagnosis in future issues.

/cc: @moltam89

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about this pull request?

Thank you,
Jorge Díaz

/cc: @moltam89

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65831. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Thank you!

**Pull request closed without merging**
