### PR TITLE
Lps 87850

### PR DESCRIPTION
**Pull request by giros**
Prerequisite:
https://github.com/matethurzo/liferay-portal/pull/2330

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:relevant

**Comment by giros** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66022. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/9293f80ad5a5~2...9293f80ad5a5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66025. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/296139ef67fc~3...296139ef67fc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66075. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c2c00bb57ac9~3...c2c00bb57ac9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
