### PR TITLE
LPS-74467

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@matethurzo kind of randomly noticed your SF commit... think this is what you meant?

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @hhuijser does this still apply after this? https://github.com/matethurzo/liferay-portal/pull/1854

**Comment by hhuijser** [comment]
@matethurzo, that one fixes the incorrect SF as well.

**Pull request closed without merging**
