### PR TITLE
LPS-68803 Do not register updateResourcePermission callbacks during site template propagation

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45116. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
