### PR TITLE
LPS-74467 Adding (Staging) suffixed descriptive name tag

### PR DESCRIPTION
**Pull request by balazssk**
Hi @matethurzo ,
I've made the changes you suggested, can you check it please?

Thanks,
Balazs

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Can you please fix the SF errors and push it again? I won't close it until.

```
     [java] Missing copyright: ./modules/apps/web-experience/staging/staging-taglib/src/main/java/com/liferay/staging/taglib/servlet/taglib/StagedDescriptiveNameTag.java
     [java] Missing author: ./modules/apps/web-experience/staging/staging-taglib/src/main/java/com/liferay/staging/taglib/servlet/taglib/StagedDescriptiveNameTag.java 15
```

**Comment by balazssk** [comment]
Thanks @matethurzo , updated!

**Comment by balazssk** [comment]
CI:retest

**Comment by balazssk** [comment]
Hi @matethurzo 
I made the updates based on your suggestions and CI gives the OK now,
Can you please have a look at this?

Thanks,
Balazs

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53309. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/95ec8b0a3b99~2...95ec8b0a3b99) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53432. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/55be3839b509~3...55be3839b509) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
