### PR TITLE
LPS-76228 Web content that links to other content in DXP fails to load upon import

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
ci:retest

**Comment by wanderlast** [comment]
ci:reopen

**Comment by wanderlast** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57409. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
