### PR TITLE
LPS-56236 Remove direct reference to MBMessage class

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @matethurzo 

This pull is part of the effort of removing Message Boards dependencies from the Comments framework. 
Can you please check it out and send to Brian if it's ok to you?

Let @adolfopa and me know if you have any doubt.

Thanks!

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @sergiogonzalez and @adolfopa,

I have a couple of question regarding this, next week I'll be in Madrid, will you guys have some time to talk about it?

Thanks,

Máté

**Comment by adolfopa** [comment]
Perfect, we'll talk about it once you're here.

See you next week :-)

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27457. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c93f3ba~3...c93f3ba) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
