### PR TITLE
LPS-89400

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67191. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c324177f7797~2...c324177f7797) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
