### PR TITLE
[TECHNICAL-SUPPORT] LPS-67872

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3429. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
