### PR TITLE
LPS-83326 pairing imported entity with it's workflowDefinitionLink element

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61870. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/5e9229da7f1c~2...5e9229da7f1c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61913. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/401a144ad73a~2...401a144ad73a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61994. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/cd36f92970da~2...cd36f92970da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63021. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/8aae9870171a~2...8aae9870171a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63178. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2c8bf5279156~6...2c8bf5279156) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
