### PR TITLE
LPS-93315 (re-send)

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @moltam89

https://issues.liferay.com/browse/LPS-93315

Re-sent from here with a fix for one of the test failures: https://github.com/brianchandotcom/liferay-portal/pull/72475

It's been a while since that PR, mostly because between working on other tickets I've been trying to see if some of the functional test failures on https://github.com/brianchandotcom/liferay-portal/pull/72475 were due to this as well. Since then after rebasing it and doing more tests with CI using my own repo, I haven't reproduced the same ones though, so I am not sure if they were related after all.

Sending it to you again first just in case you want to see it again since it has been a while.

Notes from the previous PR: 

> This change is to allow scheduled publishes to use times that can be scheduled in different time zones, rather than always defaulting to the user's time zone.
> 
> We are being pushed to "fix" this on our end, as currently there is no way for Liferay to handle staging publishes across different time zones (that may need to have their times managed separately -- for example, if some would follow daylight savings time and some wouldn't).
> 
> To accomplish this, I copied the time zone selector UI element used by the Calendar portlet and added new API that sets the time zone for the schedules created for Quartz. Quartz itself (as I've seen in my own testing) already compensates for time changes and such, so all the changes here need to do is propagate the time zone information where needed to achieve the goal of scheduling for different time zones.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
ci:test:sf

**Comment by Alec-Shay** [comment]
Hello @matethurzo,

Do you think you'll be able to take a look at this again soon to resend it? Thanks in advance!

**Comment by Alec-Shay** [comment]
Hi @moltam89,

I'm not sure if you looked at this when I resent it, but would you possibly be able to take a look again? I know it's been a while, so if you can, please let me know if there are any questions. Also if you'd like me to re-send it to you or someone else instead, let me know and I can do that as well. Thank you.

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74624. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
