### PR TITLE
[TS] LPS-83223

### PR DESCRIPTION
**Pull request by arthurchan35**
From https://github.com/matethurzo/liferay-portal/pull/2199
Hi @matethurzo , can you take a look at this PR, it's been almost a week now.

Also I noticed the commit ordered was accidentally reversed: commit 4, 5, 6 should be reordered into 6,4,5.
Final result is the same. Just to point out for easy reading.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@yuhai

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/arthurchan35/liferay-portal/pull/23. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
