### PR TITLE
LPS-64521

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-64521

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Rebased to last master

**Comment by jorgediaz-lr** [comment]
I have rebased to last master

**Comment by danielkocsis** [comment]
Reviewed and sent to Brian. https://github.com/brianchandotcom/liferay-portal/pull/38483

**Pull request closed without merging**
