### PR TITLE
LPS-55161

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @jgok

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Hey @jgok,

I've checked the code and while the bug seems to be a bug indeed, the solution I'm not sure about. So basically we have been storing these information in a persistent storage but in the code it's moved to the cache, which is not persistent at all. There is no guarantee that the cache will remain there, and this information is even not persisted across portal starts, and these information can be lost any time the cache is invalidated for some reason.

These information needs to be persisted and stored properly, but we also need to avoid the out of memory errors.

Thanks,

Máté

**Pull request closed without merging**
