### PR TITLE
LPS-74081

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @Richard678 I've reviewed the code piece, and I think it fixes the problem, but it fixes it from the wrong angle.

I've been debugging this and what happens is that the layout "1" is being imported but with a friendly url "/2" as this is the one gets assigned to it.

when the next layout "2" is being imported your code change detects the situation and sets the existingLayout to null as if hasn't been found previously.

but the thing is that this retroactively finds a false situation and tries to fix it. we should fix it when we are in the middle of importing the first page, instead of trying to fix something backwards we should fix it right away.

**Comment by Richard678** [comment]
hey @matethurzo  
A question here ...
1.Do you know the meaning of the original logic int the  LayoutStagedModelDataHandler.java

	if (existingLayout == null) {
				existingLayout = _layoutLocalService.fetchLayoutByFriendlyURL(
					groupId, privateLayout, friendlyURL);
	}
   We already  judged the layout is existing or not  by the method 
 _layoutLocalService.fetchLayoutByUuidAndGroupId(
				layout.getUuid(), groupId, privateLayout);

Why we need to judge the friendly URL?

2.And another things is :you mean the better way is to refresh the URL between loop ?
If you see the whole logic for the method doExportStagedModel ,you can find that we define all "Friendly URLs" here for each branch statement. 
For my understanding , in that case we need to refresh the URL in portletDataContext  which have some effect for other branches int the "doExportStagedModel" method.

**Pull request closed without merging**
