### PR TITLE
LPS-74855 Do not display Page Variations menu when the revision is no…

### PR DESCRIPTION
**Pull request by akosthurzo**
…t enabled

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:reopen

**Comment by akosthurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52170. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52490. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
