### PR TITLE
LPS-75581 Copy from Live doesn't bring content to staging

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Máté,

It was a somewhat big modification. I Hope it works.

Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by peterborkuti** [comment]
Hey @matethurzo , I'd like Marcsi to test it before forwarding. ( I mean, If you happen to think it is good enough for forwarding).

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53172. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
