### PR TITLE
Lps 81695 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59660. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c4e61b0fe7cb~3...c4e61b0fe7cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
