### PR TITLE
LPS-79577 Hide staging configuration icon when we don't have a portlet data handler or it is not properly implemented

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi Máté, we really need an option to hide Staging configuration icon in case when we don't have corresponding PDH implemented. Right now every portlet has DefaultPortletDataHandler which makes no sense because it doesn't export/import anything.

cc @ealonso

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57184. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e0e0faeb7681~1...e0e0faeb7681) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
