### PR TITLE
[TECHNICAL-SUPPORT]  LPS-85498

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-85498

This change should improve the supportability of this code.
Thanks!

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
Hi @matethurzo!
Semantic versioning issues are not related to this commit, I just add an "if" to avoid a NPE.
Please just let me know if you need anything.
Thanks!

**Comment by JosemariaMunoz** [comment]
Hi @matethurzo!
Did you have time to review this PR?
Thanks!

**Comment by zsoltbalogh** [comment]
Notified Máté separately.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63501. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JosemariaMunoz** [comment]
Thanks a lot @matethurzo , @zsoltbalogh !!

**Pull request closed without merging**
