### PR TITLE
LPS-81375 portal-impl GroupLocalServiceImpl friendlyUrl fix

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59151. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/ecbfa76e76de~1...ecbfa76e76de) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59569. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/821a50475288~1...821a50475288) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
