### PR TITLE
LPS-78411 Use project dependency

### PR DESCRIPTION
**Pull request by giros**

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by balazssk** [comment]
Hi @matethurzo ,
Have you had a chance to look this review through?

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56036. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
