### PR TITLE
LPS-62130

### PR DESCRIPTION
**Pull request by LeventeHudak**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/1330. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/kmaria/liferay-portal/pull/12. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
