### PR TITLE
Lps 75365

### PR DESCRIPTION
**Pull request by mtambara**
Roll back deprecations as discussed in https://github.com/brianchandotcom/liferay-portal/pull/55464

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55599. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
thanks @mtambara

**Pull request closed without merging**
