### PR TITLE
Lps 77336 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by akosthurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62165. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/6b142b5311ae~1...6b142b5311ae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62227. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/af60d14f5200~2...af60d14f5200) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
