### PR TITLE
LPS-57021

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
@matethurzo I will be on holiday for three weeks, I will return the *August 10*

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey, I've checked this pull request too, but before we merge it in I'd like to validate a couple of things. What I'd like to verify if we can turn the AssetLink to a StagedModel, so the deletions would be supported by default by the framework itself, and we wouldn't need to hack anything. Please give me some time to investigate. Thanks

**Comment by jorgediaz-lr** [comment]
@matethurzo I think changing AssetLink to a StagedModel cannot be backported to 6.2.x, Isn't it?

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo ,

Do you have any update about "changing AssetLink to a StagedModel"?

Perhaps we can commit this solution and create a new LPS to handle that improvement.
This will allow us to include the solution to this bug in a fixpack at 6.2.x as soon as possible.

Regards

**Comment by matethurzo** [comment]
Yes I think we can send this to 6.2.x and we can work on a different solution for master. I'll take care of this on master too. Thanks!

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

Did you created a LPS about master solution of this bug?

Thank you

**Comment by matethurzo** [comment]
I have now. Sorry for the delay: https://issues.liferay.com/browse/LPS-58452

I've already started working on this.

Thanks

**Comment by jorgediaz-lr** [comment]
@matethurzo 

I am going to send this pull request for 6.2.x as LPS-58452 is a new functionality and won't be backported

Thank you

**Comment by matethurzo** [comment]
Thanks!

**Pull request closed without merging**
