### PR TITLE
LPS-84643

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-84643

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by giros** [comment]
The errors seem unrelated.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62899. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
