### PR TITLE
[TECHNICAL SUPPORT] LPS-54392

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-54392

I sent first LPS-54392 pull request to @moltam89 here https://github.com/moltam89/liferay-portal/pull/433 and he suggested some changes.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about this pull request?

I would like to send this fix to the customer as soon as possible.

/cc @moltam89 as SME of Staging functionality, can you talk product team in order to unblock this pull request review?

Thank you

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62133. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
