### PR TITLE
LPS-80439 Use proper checkbox label

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-80439

cc @palius

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58055. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
ci:stop

**Pull request closed without merging**
