### PR TITLE
LPS-89401 ChangeTrackingPublishWithBackgroundTask test added

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
@danielkocsis

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by zoltancsaszi** [comment]
ci:test:stop

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67075. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/365ba548afec~3...365ba548afec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
