### PR TITLE
LPS-88848

### PR DESCRIPTION
**Pull request by giros**
This is a follow up PR for https://issues.liferay.com/browse/LPS-88848 as it started to log errors during tests that did not have a user set in PrincipalThreadLocal.

Applying now what @ealonso suggested on https://github.com/matethurzo/liferay-portal/pull/2371

Test result: https://github.com/giros/liferay-portal/pull/78

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant @matethurzo can you please review?

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67020. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:stop
testing CI commands, please ignore

**Pull request closed without merging**
