### PR TITLE
[TECHNICAL-SUPPORT] LPS-71050

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Alec-Shay

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Alec-Shay** [comment]
Hi @matethurzo,

Just checking up on this as it's been a while since this was opened. Will you be able to review this soon?

Thanks!

**Comment by matethurzo** [comment]
Pull request forwarded to https://github.com/danielkocsis/liferay-portal/pull/623. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/fea8bd8d118f~8...fea8bd8d118f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
