### PR TITLE
Lps 76847 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@akosthurzo I've checked the code, generally it looks good, expect one thing, the changes cause a major version increase in the background task api bundle, which is a potential problem for customers and consumers of this API.

Please change that to avoid major change and re-send.

Thanks!

**Comment by akosthurzo** [comment]
@matethurzo it seems it is because of what's changed in the persistence package, which is generated code

**Pull request closed without merging**
