### PR TITLE
LPS-69357 SF

### PR DESCRIPTION
**Pull request by inacionery**
/cc @rafaprax @marcellustavares @juliocamarero

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
Hey @matethurzo,

those CI errors are unrelated.

Thanks!

**Comment by rafaprax** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @inacionery @matethurzo,

Do you have any updates about this pr?

Thanks!!!!

**Comment by inacionery** [comment]
Not from my side, @matethurzo do you have any?

Thanks!!! 😄

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
