### PR TITLE
[Technical Support] LPS-76116 Making the LAR database agnostic for Timestamp types

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-76116

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54352. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c574fa393f4b~1...c574fa393f4b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54537. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/d51a8e1634dd~1...d51a8e1634dd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
