### PR TITLE
LPS-54744

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @arbetts

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by arbetts** [comment]
Hi Mate,

any update on this?

**Comment by matethurzo** [comment]
I'll start today, but it seems to be lot of modification. I'll update you with my progress

**Comment by matethurzo** [comment]
Sorry for the delay Andrew, I'll start it soon

**Comment by arbetts** [comment]
Thanks Mate! :)

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Closing this for now, based on our discussions w/ @arbetts he is going to resend to me once he is ready.

Thanks!

**Pull request closed without merging**
