### PR TITLE
LPS-54544

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dustinryerson

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@danielkocsis will handle this, thanks.

**Comment by danielkocsis** [comment]
Hi @jonathanmccann, @arbetts 

I have tested the generic behavior of the portal and it seems when I remove an instantiable portlet from layout some automatism removes the belonging portlet setting. So I think the proper fix is to find and fix this mechanism to remove those portlet preferences as well, and to create a maintenance task to find these preferences occasionally.

Could you please resend?

thanks,
Daniel

**Comment by arbetts** [comment]
Hi @danielkocsis ,

The behavior I am fixing is specific to LayoutRevisions.

Here is my thought process behind this fix:
1) We use the layoutRevisionId for the plid column in the portletPreferences for layoutRevisions, so when a portlet is removed from the layoutRevision, the portlet's portletPreferences is fetched with the wrong plid. 
2) PortletPreferencesLocalServiceStagingAdvice swaps the plid for the layoutRevisionId so that when Page Versioning is enabled the correct plid is used.
3) When deleting portletPreferences we assume that the plid passed in is the correct value (which stays true to the API).
4) Because of the above reasons, I think fixing this in the place where we delete the preferences is incorrect because this means that the developer must know which "getPreferences" methods are handled by the advice and which ones are not.
5) The advice should cover all of the different cases for "getPreferences" in PorteltPreferencesLocalService.

The method where we handle deleting the portletPreferences is:
com.liferay.portal.service.impl.PortletLocalServiceImpl#deletePortlet 

and it uses 
		List<PortletPreferences> portletPreferencesList =
			portletPreferencesLocalService.getPortletPreferences(
				ownerType, plid, portletId);

to fetch the portletPreferences to delete

I've send another pull for you to review https://github.com/danielkocsis/liferay-portal/pull/438

**Pull request closed without merging**
