### PR TITLE
LPS-69069 Use @Reference instead

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
Hi @matethurzo ,

@hudakl 's solution fixes LPS-69069 for Web Content Display. An equivalent solution should be applied to other cases (namely, DDLDisplay, WikiDisplay, PollsDisplay and AssetPublisher) for consistency. I think we can move this one forward and apply the changes to other cases later and document it.

Thanks

@juliocamarero

**Comment by epgarcia** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@epgarcia this should have been sent to the separate journal repo no?

**Comment by epgarcia** [comment]
Hi @matethurzo,

Yes, you're totally right. The CI closed @hudakl 's original pull for this reason but I didn't realize. Sorry, I'll send it to the journal repo. 

Thanks

**Comment by epgarcia** [comment]
See liferay/com-liferay-journal/pull/74

**Pull request closed without merging**
