### PR TITLE
LPS-88490 Create ServiceContext before overriding entityId so Categories and Tags remain mapped in _assetCategoryIdsMap

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @matethurzo,

I'm forwarding this to you, as this undoes some of the refactoring work you did with the StagedModelRepository.

It is not clear to me if this can be solved cleanly with the current repository API. If you think so, feel free to apply or suggest any changes.

Comment from the original PR:

> https://issues.liferay.com/browse/LPS-88490
> https://issues.liferay.com/browse/LPP-32496
>
> Problem: Overwriting the EntryId before the updateStagedModel() makes the serviceContext will cause the assetCategory and assetTag maps to try looking up by the wrong BookmarkEntry id.
>
> Solution: Instead, initialize the serviceContext beforehand just like Blogs does.
>
> I did check all the other StagedModelDataHandlers where duplicates of the original code existed: AssetDisplayPageEntry, AssetListEntry, AssetListEntryAssetEntryRel, BookmarkFolders, DDLRecordSet, DDMFormInstance, FragmentEntry, FragmentCollection, FragmentEntryLink, LayoutPageTemplateCollection, LayoutPageTemplateStructure, LayoutPageTemplateEntry, SiteNavigationMenu, SiteNavigationMenuItem - but none of these appear to be using Categories and Tags so no changes are necessary.

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by joshuacords** [comment]
Hello @matethurzo,

When you have a chance, could you give a rough eta for when you'll be able to review this.

Thank you.

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
hey @joshuacords this is not really a clean solution, the SMR is completely being left out in one case, I think that's confusing.

the same code is duplicated in the repository also, so simply can't we just pass the imported entry as it is to the repository and then that's it?

**Comment by matethurzo** [comment]
ci:stop

**Comment by joshuacords** [comment]
Hello @matethurzo,

I can see why it's not a clean solution, however I don't see a better direction to take without a major reworking. 
Understand BookmarksEntryLocalServiceImpl.updateAsset() which populates the AssetCategories and AssetTags, depends on the information in the ServiceContext: https://github.com/joshuacords/liferay-portal/blob/35e07380c599c338fb7e7b20c58a9b9c2efd088a/modules/apps/bookmarks/bookmarks-service/src/main/java/com/liferay/bookmarks/service/impl/BookmarksEntryLocalServiceImpl.java#L634-L638

The ServiceContext initializes the AssetCategories and AssetTags when called from BookmarksEntryStagedModelDataHandler.doImportStagedModel() here: https://github.com/joshuacords/liferay-portal/blob/0397da87d4353a608b65e82ad2527873ea5df9c5/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/PortletDataContextImpl.java#L2289-L2298

When I remove the `importedEntry.setEntryId(existingEntry.getEntryId());` code as suggested, the incorrect BookmarkId will not be found here: https://github.com/joshuacords/liferay-portal/blob/35e07380c599c338fb7e7b20c58a9b9c2efd088a/modules/apps/bookmarks/bookmarks-service/src/main/java/com/liferay/bookmarks/service/impl/BookmarksEntryLocalServiceImpl.java#L614-L615 which throws an Exception and fails.

And by default, using the `_stagedModelRepository` will force the ServiceContext to be populated with the wrong model's categories and tags, and the existing model or id would need to be added as a parameter to the `_stagedModelRepository.updateStagedModel()` if we wanted to still use the SMR.

I've noticed other StagedModelDataHandlers don't use the `_stagedModelRepository`, such as Blogs and JournalArticles, in fact I can't find a single other StagedModelDataHandler that makes use of Categories/Tags while using `_stagedModelRepository`.

Could you suggest a better alternative?

**Comment by matethurzo** [comment]
@joshuacords All I'm saying is handling the update in the same class, don't separate to different places.

See DDMFormInstanceRecordSMR and DDMFormInstanceRecordSMDH. The SMR has custom methods because they needed the special logic, then just do the same for bookmarks.

The update logic is not separated to different places it's more consistent

**Comment by joshuacords** [comment]
Thank you @matethurzo, I'll look into making that change.

**Comment by joshuacords** [comment]
Resending: https://github.com/SamZiemer/liferay-portal/pull/537

**Pull request closed without merging**
