### PR TITLE
LPS-66069 Since Global DDMStructures only have a live site version and not a staged version, try using the portletDataContext to fetch the DDMStructure first

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @matethurzo, could you please double check @mbowerman  fix?

There was some discussion https://github.com/marcellustavares/liferay-portal/pull/1449

Thanks

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @marcellustavares @mbowerman,

I understand the DDLRecordSetPermission changes but I do not understand why do we need to change the DDMStructureSMDH? The commit description is not valid global can have a stage and a live version as well, and also the logic has been change calculates the proper group id for everyone during the process. Why would we override it with the scope group id? 
That seems to be broken at the first glance, can you please explain the purpose of that change?

Thanks,

Máté

**Comment by mbowerman** [comment]
Hi @matethurzo,

When I tested my changes to DDLRecordSetPermission, I discovered a bug where if you publish a DDLRecordSet to live using a global DDMStructure, the DDLRecordSet gets the ddmStructureId that corresponds to the live site. However, when you publish DDLRecords from staging to live, the ddmStructureId attached to the DDLRecordSet changes to the ddmStructureId corresponding to the global site. If you had already added records on the live site, they will get deleted because it thinks that you are publishing a change to the structure.

The changes to the DDMStructureSMDH this bug from occurring by modifying the way we get the ddmStructureId. Now, it will return the ddmStructureId attached to the live site if it exists, and it will use the groupId from the referenceElement otherwise. This prevents the DDLRecordSet from having its ddmStructureId modified when you publish DDLRecords.

**Comment by matethurzo** [comment]
hey @mbowerman thanks for the explanation, but I'm still a little bit foggy on the details. If I understand correctly the permission bug and this are two separate issues, can we split them to two? So we can continue a conversation separately.

**Comment by mbowerman** [comment]
Hi @matethurzo,

Yes, if you'd like you can remove the second commit and we can open up a new ticket for that bug. I only fixed it in this one because fixing the first bug brought it to light.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40724. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@mbowerman dropped the second commit, and push to Brian the first. Can you please open a ticket for the other, so we can investigate?

Thanks,

Máté

**Comment by mbowerman** [comment]
Hi @matethurzo,

Thanks for reviewing the pull! I've gone ahead and created [LPS-66573](https://issues.liferay.com/browse/LPS-66573) as requested.

**Pull request closed without merging**
