### PR TITLE
LPS-89210

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69278

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69362. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e360da1a154c~2...e360da1a154c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2503. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/75ff3e9b8f11~3...75ff3e9b8f11) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69445. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/7c4998af4d6c~5...7c4998af4d6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2510. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/7c4998af4d6c~5...7c4998af4d6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2512. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e31ee7f83ccb~5...e31ee7f83ccb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69519. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e31ee7f83ccb~5...e31ee7f83ccb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2526. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/51ef94c9ce03~9...51ef94c9ce03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2529. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3743a5405ff2~11...3743a5405ff2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2535. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/4d86df382443~3...4d86df382443) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
