### PR TITLE
LPS-58631

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
**Important:** pull request https://github.com/matethurzo/liferay-portal/pull/1187 must be commited before commiting this one

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by danielkocsis** [comment]
Checked. Pull request submitted to: https://github.com/sergiogonzalez/liferay-portal/pull/2595

**Comment by jorgediaz-lr** [comment]
thank you @danielkocsis !

**Pull request closed without merging**
