### PR TITLE
LPS-89170

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ct:test

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:stop

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/658. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
