### PR TITLE
LPS-56312 An excepcion of "layoutset does not exists" is thrown during Staging Activation

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @matethurzo 

I have been doing some tests at master with a real database of a customer upgraded from 6.2 to 7.0 and this is one of the issues I have detected:
   - public pages activation process spends 4 hours and after that time a NPE is thrown. So staging group is deleted
   - but after that private pages activation process is executed and after one hour of export process this "layoutset does not exists" is thrown because at public page process we deleted the group.

This code avoids spending 1 hour of export process for private pages when we know that it is going to fail for sure.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

I have also rebased this pull request

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about the review of this pull request?

Thank you

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

I have rebased all my pulls to last master level.

My code is unchanged

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

I have rebased all my pulls to last master level.

My code is unchanged

**Comment by matethurzo** [comment]
Thanks, I'll review this soon

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37688. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/8b3a8aa~1...8b3a8aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
