### PR TITLE
LPS-83326 workflowDefinitionLink import fix

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
Hi @ChrisKian ,

I had to modify my solution, it should work.
https://github.com/matethurzo/liferay-portal/pull/2218
Could you test it as well?

Thanks!

**Comment by ChrisKian** [comment]
Hi @zoltancsaszi,

After testing your changes [here](https://github.com/matethurzo/liferay-portal/pull/2218), I can confirm the issue I have been seeing is now resolved.  Thank you for looking into this!

**Pull request closed without merging**
