### PR TITLE
[Technical-Support] LPS-75041

### PR DESCRIPTION
**Pull request by yuhai**
Hi @matethurzo ,

The original PR was from https://github.com/matethurzo/liferay-portal/pull/1759.

We get feedback from @dacousalr. Do you have a chance to review this?

cc @dacousalr, @zsigmondrab

Regards,
Hai

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@yuhai @dacousalr @zsigmondrab i need some time to go through this pull i'll be able to give an answer tomorrow.

**Comment by yuhai** [comment]
Hi @matethurzo 

Hope you are well.

Do you have a chance to review the PR?

Regards,
Hai

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52941. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
