### PR TITLE
LPS-86383 default serverPort fallback added, sync rule, cleanUp

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
ci:stop

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65878. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
