### PR TITLE
[TECH SUPPORT] LPS-74437 ORMException is thrown after updating a site template when the portal is under load

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @dacousalr the change seems to be okay, but i'm not sure how the ORMException is related to the change? There is only some logging changes, so I'm confused how is that solving the issue

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
closing while waiting on answer from @dacousalr

**Comment by dacousalr** [comment]
ci:reopen

**Comment by dacousalr** [comment]
Hi @matethurzo,

Clarifications about why this solution is as is are [here](https://issues.liferay.com/browse/LPS-74437?focusedCommentId=1109337&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1109337).

Best

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51574. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
