### PR TITLE
[TECHNICAL SUPPORT] LPS-83849 Avoid warnings during export/import

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-83849

**This LPS was detected during [LPS-82757](https://issues.liferay.com/browse/LPS-82757) resolution.**

In case of having a link with friendly url:
  - http://localhost:8080/web/mysite/mypage/-/portlet/friendly/226268/226312
a warning is produced.

To avoid that warning, I am using "/-/" as separator, so we only process the page link until "/-/" characters.

**Other changes:**
 - About https://github.com/matethurzo/liferay-portal/pull/2211/commits/dd3e5a8ab2c27bd9bb2c01abdeb81535daa0a6bb it was added in [LPS-82757](https://issues.liferay.com/browse/LPS-82757), but I have realized that is not used (I created the JournalFeedReferences content processor from a copy of document library, and there this code was related to recycle bin)
 - About https://github.com/matethurzo/liferay-portal/pull/2211/commits/3b37083faea765f3bf5a7ad36e2f92c3f6542807 in [LPS-82757](https://issues.liferay.com/browse/LPS-82757)  we are replacing **/-/journal/rss/...** url fragment with **[$journalfeed-reference=...]** that causes problems with new LPS-83849 code, that search the "/-/" string.
To avoid that, I am changing JournalFeed replacement: **/-/journal/rss/...** is now rewritten to **/-/[$journalfeed-reference=...]** 

/cc: @moltam89

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61701. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/cc111e6544fb~1...cc111e6544fb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
