### PR TITLE
LPS-86364 buildLang

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by diana-lin** [comment]
Hi All,

It looks like this PR may be ready to be merged.  Please let me know if there is anything else that's needed in order for this to happen.  Thanks!

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @zoltancsaszi, is there anything that needs to be done to move forward on this PR?

**Comment by zoltancsaszi** [comment]
@matethurzo Could you check it please?

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69038. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
