### PR TITLE
LPS-59502

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi Mate,

This is kind of urgent for the customer, Is it possible that you can review this with a higher priority?

Best Regards,
Hai

**Comment by matethurzo** [comment]
yes I'll review it soon.

**Comment by matethurzo** [comment]
Hey @yuhai,

I've checked this change, and I think the proper solution would be to check why the permission checker is null at that point.
Probably when performing the import from the UI the PermissionCheckerThreadLocal is properly initialized. On the other hand the resources importer will subscribe to the hot_deploy message destination and the execution will start running from there. Probably at that point either the messaging framework, or the resources importer do not initialize the PermissionCheckerThreadLocal.
If we just bypass the permission checking, we might create security regressions in the asset publisher.

Can you please investigate when the thread local is not initialized properly when using the resource importer?

Thanks,

Máté

**Comment by matethurzo** [comment]
@yuhai After further investigation it turned out that the message listener is running on a new thread, probably that's the reason why the permission checker is not initialized on that thread. The proper solution is to make sure the permission checker is also initialized there.

**Comment by yuhai** [comment]
Hi Mate,

I want to explain why we don't set permission checker in message listener.

When use resources-importer-web to import site lar, due to the user is defaultUser who deploys one portlet so that resources-importer-web can be invoked to import lar, in this process, we don't set PermissionThreadLocal.setPermissionChecker(), so when asset publisher configuration includes "scopeIds:values", the NPE will occur.

DefaultUser own Guest Role(that is to say, defaultuser is guest user), so he won't own update permission. Due to the guest user, this is reason why the permission check is not initialized.

The fix refers to SitesImpl.setLayoutSetPrototypeLinkEnabledParameter(){1954 lines} to instead of setting the PermissionThreadLocal.setPermissionChecker() in resources-importer-web.

Why the user is defaultUser?
Please refer to the below logic.
ResourcesImporterHotDeployMessageListener.importResources()->ImporterFactory.createImporter()->configureImporter() (importer.afterPropertiesSet();)-> BaseImporter.afterPropertiesSet()

Should I initialize Permission checker for guest user?

Thanks,
Hai

**Comment by matethurzo** [comment]
Hi @yuhai,

Thank you for the detailed explanation.

I was looking at the resource importer code, and as you have explained as well, we are using the default user to do everything, the importing and executing the processes and everything else. So I think we should initialize the permission checker to the same user. So in case we want to change that user we are going to change at this single place and it will be effective for the whole process.

Thanks,

Máté

**Comment by yuhai** [comment]
Hi Máté,

Please see the related fix from https://github.com/matethurzo/liferay-plugins/pull/40. The fix initializes the permission checker in resource importer. Please review it when you have free time.

Thanks,
Hai

**Pull request closed without merging**
