### PR TITLE
LPS-88405

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
ci:test:df
ci:test:change-tracking

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66393. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/d3f0c2af28da~1...d3f0c2af28da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
