### PR TITLE
[TECHNICAL-SUPPORT] LPS-77018

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
@matethurzo A little different than discussed since ```staging-process-web``` didn't need ```BackgroundTask``` due to it being further limited by ```ExportImportConfiguration``` whose name length is 200 vs 255.

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55035. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
