### PR TITLE
LPS-88735 Access ClassName value directly

### PR DESCRIPTION
**Pull request by cleydyr**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by cleydyr** [comment]
Hey, @matethurzo. I think that the mentioned failures are false positives. The code I've changed relates only to remote staging.

The first one, LocalFile.CPDocumentsandmedia#AddShortcutToSiteDocument, doesn't even involve staging AFAIK.

The second one involves local staging, but has happened before, according to 
the [Testray report for this pull](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=454126048).

Regards

**Comment by cleydyr** [comment]
Hey, @matethurzo. Is there anything we can do to advance this fix's merging to master?

Thank you

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66664. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
