### PR TITLE
[TS] LPS-75041

### PR DESCRIPTION
**Pull request by yuhai**
cc @hhuijser, 

Hi @matethurzo,

The root issue: If the user owns "View Staging" permission, the user can access to staging page (we remove staging page "view" permission, the user shouldn't access.)

Please refer to https://github.com/yuhai/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/theme/NavItem.java#L97, navigation will be replaced by themeDisplay.getLayouts(); And themeDisplay.setLayouts(layouts) is in https://github.com/yuhai/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/events/ServicePreAction.java#L769

The commit "LPS-6432 Divide Manage Pages into atomic actions / Fix Power User role" added that the user with "view staging" permission can access to those staging page (the user doesn't own "view" permission for this staging page).

When the user owns "View Staging" permission, it shouldn't mean the user can view staging pages. For one staging page, if we remove "view" permission for the user, the user shouldn't access to this page even though the user owns "View Staging" permission.

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @yuhai but I'm not convinced we should change this.

You removed lot of code handling this specific use case, which tells me that in the past this was the desired behavior, this is not a simple bug.
Even if we remove this and change the behavior this would mean a permission change for all the customers that install the fixpack, and this could case regression for them if they have a permission setup different than the one your are creating the fix for.

I'm not comfortable sending this to master without having a broader agreement from support and product that this is not going to cause more issues for our customers.

Will defer further conversation to email

**Comment by zsigmondrab** [comment]
Hi @yuhai,

I will have time to take a deeper look at this one tomorrow only also. After a shorter look at, it seems to be dangerous to remove that code to me also, because I cannot see yet what this change can cause at other parts.

Till then, I would have some questions for which you may know the answers immediately.

Have you tried to find the reason of having that check that you want to remove now? From git history, some annotation, blame or something?

Was the code introduced with the LPS-6432 changes?

In addition, from [the simplified steps to reproduce](https://issues.liferay.com/browse/LPS-75041?focusedCommentId=1155314&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1155314), is there any other permission for page2 that you keep when you remove the VIEW one?

Thanks in advance,
Zsigmond

**Comment by yuhai** [comment]
Hi @zsigmondrab 

Thanks for your check.

Yes, I tried to find the reason. Please refer to the fix detailed explanation from https://github.com/matethurzo/liferay-portal/pull/1759#issue-262993074

The code was introduced with LPS-6432 (by the way, ).

Actually, for page2 permission, you may remove all permission or remove view permission for the user, if the user owns "View staging" permission, the user can see the page2 in staging site.

Regards,
Hai

**Comment by zsigmondrab** [comment]
Huhhh, ok, as it's implemented a long time ago, it's not an easy one.

@matethurzo, can we have a talk about this in person, because it doesn't seem to me logical to me either.

Thanks

**Comment by zsigmondrab** [comment]
Forwarded to https://github.com/dacousalr/liferay-portal/pull/27

**Pull request closed without merging**
