### PR TITLE
LPS-52400

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by matethurzo** [comment]
ok to test

**Comment by matethurzo** [comment]
This is probably not a good solution, I'm emailing regarding this.

Thanks.

**Comment by yuhai** [comment]
Hi Máté,

Hope you are doing well.
Could you please check the below explanation?

Bypassing layout is merge-fail-friendly-url-layouts and site template page won't be imported to really site. In for loop, we used all site template layouts to iterate. Due to we don't import those conflict friendlyURL layouts from site template. So the NPE occured.

I think the below comment can explain the issue clearly.
https://issues.liferay.com/browse/LPS-52400?focusedCommentId=556584&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-556584

Please kindly let me know if you have other concerns.

Thanks,
Hai

**Comment by matethurzo** [comment]
Thanks for the explanation, I'll check the steps soon.

**Comment by matethurzo** [comment]
Hey,

I've investigated the issue.

The primary problem is - as you wrote - that the site template changes cannot be propagated to the site itself, because the two pages have the same name. In this case there should be an error message on the site settings dialog in the details section warning the user that an error has happened and it should be resolved manually.
Once it's resolved manually they can reset and re-try to propagate the changes.

I've tested the ticket and there is a problem on the UI: it does not show what was the problem - it only shows that there was a problem.

We should move forward with this issue the following way:
- Check why the UI does not show which page was failing to merge and fix that problem, because otherwise the user won't know what has failed.
- The original fix can be applied but with a modification. Besides a null check it's not enough to just continue the loop, we should print a warn message to show at least in the log, that something not normal has happened there.

Can you please take care of these items?

Thanks!

**Pull request closed without merging**
