### PR TITLE
LPS-71912 <em> should not appear in are-you-sure-you-want-to-merge-changes-from-x since it's display in an alert message.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @matethurzo,
 did you have chance to take a look to this PR?
Thanks in advance.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @marianoalvarosaiz sorry for the delay. I've checked the code and mostly it looks great, except one thing.

Please resend without the static block in the JSP. otherwise it looks good.

Thanks!

**Comment by marianoalvarosaiz** [comment]
Thanks for the feedback @matethurzo. Just a question, what's the reason of the need to remove the static keyword since it's a method w/o state?

**Comment by marianoalvarosaiz** [comment]
Hi @matethurzo,
 did you have time to take a look to the previous question about the reason of removing the static keyword?
Thanks in advance.

**Comment by matethurzo** [comment]
@marianoalvarosaiz sorry for the delay i missed the comment.

i meant not the static keyword itself, the static is indeed fine as you write, but it's an antipattern to put static methods or utility methods like this in JSP.

What I wanted to ask is to remove the static block completely.

**Pull request closed without merging**
