### PR TITLE
LPS-65485

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
@matethurzo have you had a chance to look at this yet?

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@arbetts what's the performance improvement part in the pull? There are lots of refactoring, but it's difficult to differentiate. Also do you have any measurement of the performance improvement? When we are doing performance improvements I like to have a measurement in place to make sure we are not just reorganizing the code.

It seems like the pull contains a set of changes that modifying the same code pieces but separate problems/improvements. Is it possible to break this up into smaller pieces? it would be way easier to review and fine tune the changes. For example you have removed the company preference export, because it's not imported and while it seems to be right, I'd like to investigate more just on that, if we really can drop that. Or what was the purpose of it.

Last we'll need a test or more likely more test cases. This pull is essentially reorganizing one of the key parts of staging and export import and given that it is risky. if the functionality does not change, since it's only performance, we will need tests to ensure that the before/after results and outputs are the same.

**Comment by arbetts** [comment]
@matethurzo heres some explanation of my changes:

Even though the diff looks big, I am not actually changing any of the existing logic. If we have test coverage for this code already, then no new cases have been added. The preferences are fetched the same way and the same flow of control still applies. Now It is just not more obvious what we are doing.

performance improvements:
1) removing unnecessary flow of control checks (like layout == null and layoutTypePortlet == null) ef2b75ff2
2) pulling duplicate flow of control checks to outermost position. 0993edba and 61bfacccf
3) dont refetch model from DB, especially with a different method that is not going to be cached from the previous query. 1ba9905 lines 795 through 805.
4) eliminates unnecessary flow of control check. 351f9acb
5) write less data into LAR. fa33e6f
6) return null before parsing the xml document. 1fc0c82e3
7) write less data into LAR. cf0bf8bd1

In order to make these performance improvements, i needed to refactor the code. I can't combine the flow of control as is because it is split up in different method calls. i can't eliminate the duplicate fetch to the DB because it is in a different method, and i can't exit before parsing the xml without doing the same code changes twice because of the duplicate logic.

I have not measured the performance impact of these changes. I can run some measurement tests and get back to you about it.

**Comment by matethurzo** [comment]
hey @arbetts we have been discussing this a long time ago, and as far as i can remember we have agreed that we will re-iterate this after the release. 

I also remember that we have been discussing some measurements needs to be done, since it's a performance improvement we need to see if the changes are actually working.

have you been spending time on this since then?

**Comment by arbetts** [comment]
hi @matethurzo 

I remember our discussion and you are right, we were going to revisit this after release :). 

I have not been spending time on this. I have since moved from Support to Global Services so my time is now focused on client projects.

However, I have thought about this change. I think looking at this change as a performance fix might be misleading. Whereas it may improve the performance of our export import of portlet preferences, the main idea is to clean up the code; making it easier to find and fix future bugs. 

The performance aspect of this change originated from discussions with the client, but we quickly realized that the impact of this change was because of the clients customizations. 

I don't know if you would like to still pursue this change, I do not think i will have time to work on it.

**Pull request closed without merging**
