### PR TITLE
LPS-73137

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@matethurzo see https://github.com/brianchandotcom/liferay-portal/pull/50398

**Comment by brianchandotcom** [comment]
I stopped my tests on CI to save on resources.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50522. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/54e3fbdcf13d~1...54e3fbdcf13d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50569. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a368b24a84f2~2...a368b24a84f2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
