### PR TITLE
[TECHNICAL SUPPORT] LPS-88570 Add error trace in case of unexpected error in ExportImportLocalServiceImpl.

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-88570

We need to add a **_log.error** trace in case of ExportImportRuntimeException as it is a generic error and we cannot diagnose customer issues without it.

/cc: @moltam89

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66135. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
thank you, @matethurzo

**Pull request closed without merging**
