### PR TITLE
LPS-82757 New JournalFeedReferencesExportImportContentProcessor that rewrites the links to JournalFeeds objects

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-82757

I am adding a ExportImportContentProcessor that rewrites the links from webcontents to a JournalFeed

@ealonso @pavel-savinov please, also take look to the pull (related to [PTR-374](https://issues.liferay.com/browse/PTR-374))

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

I was on holidays, I have just return today. 

Please let me know any question related with this solution.

Thank you!

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about this pull request?

We want to solve this LPS and backport to 7.0.x ASAP in order to include it in a fixpack.

Please let me know any question related with this solution.

Thank you,
Jorge Díaz

**Comment by jorgediaz-lr** [comment]
After some @moltam89 comments by email, I have created a new pr, see: https://github.com/matethurzo/liferay-portal/pull/2205

**Pull request closed without merging**
