### PR TITLE
J cords lps 81083

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-81083
@SamZiemer @jonathanmccann

Hello Mate,

I replaced the Util call to a localService call.

 - Old Notes - 
I fixed the issue that was still present after https://issues.liferay.com/browse/LPS-78292 where layout revisions of other layout set branches (Site Page Variations) would be published. This resolves all the issues I have found related to publishing the incorrect content.

_layoutRevisionLocalService.getLayoutRevisions() should always return at most 1 result when head = true as there's only one head LayoutRevision per layoutSetBranch.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/giros/liferay-portal/pull/70. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by joshuacords** [comment]
Thanks for reviewing this so quickly @matethurzo ! :)

**Pull request closed without merging**
