### PR TITLE
LPS-87698

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65738. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/fa099b98c047~8...fa099b98c047) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65740. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/69b3c1cd4714~8...69b3c1cd4714) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65787. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a85cc4f5905f~8...a85cc4f5905f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65789. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c26585fba2c0~9...c26585fba2c0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65794. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/5282b7e40f83~10...5282b7e40f83) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65797. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/9b10fc5c3340~12...9b10fc5c3340) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
