### PR TITLE
LPS-56655

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30203. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c54830e~3...c54830e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30246. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/0fefc32~3...0fefc32) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
