### PR TITLE
LPS-79589 Implicitly update all parent layouts' latest layout revisio…

### PR DESCRIPTION
**Pull request by giros**
…n when a layout revision is updated on the staging bar portlet

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by giros** [comment]
I kind of expected to break some tests :) Looking into this, will resend.

**Comment by giros** [comment]
Turns out these are irrelevant and they fail for others as well for some reason. So I'm reopening this.

**Comment by giros** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59922. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
