### PR TITLE
LPS-78789 part 1

### PR DESCRIPTION
**Pull request by palius**
Hi @matethurzo,

This is the first part of the ticket, just some tag improving.

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by peterborkuti** [comment]
Sorry, Máté, I do not understand test results. I clicked on the link of the failed test, but that page displays: 
"Test Result (no failures)". I spent 30 minutes with figuring out what this is, but now I feel I am too old for this.

**Comment by peterborkuti** [comment]
I will add some more commits to this today.

**Comment by peterborkuti** [comment]
@palius , @matethurzo 
This pull should be closed. I am sending another one with two additional commits.

**Comment by palius** [comment]
@peterborkuti, @matethurzo
I'm closing this.

**Pull request closed without merging**
