### PR TITLE
Changeset api

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57875. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57924. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/44abc1e8cb49~4...44abc1e8cb49) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57962. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a1af68f6c7bc~5...a1af68f6c7bc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58011. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/7289def6267b~5...7289def6267b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
