### PR TITLE
Lps 82446 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by akosthurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by akosthurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60532. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/d6e872c8be93~1...d6e872c8be93) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
