### PR TITLE
[TECHNICAL-SUPPORT] LPS-79800

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @joshuacords:

> Here's what's behind these changes. When exporting portlets the most recent layoutRevision was being used instead of the latest layoutRevision set as Head. This causes the portlets configurations to reference the last revision instead of the last revision marked as "Ready for Publication". In order to change this I tried changing the [StagingImpl.getRecentLayoutRevisionId](https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/staging/StagingImpl.java#L3324-L3380) method. However, that change affects many other calls, including how the layoutRevision to view in Staged Version is returned, breaking it. I'm convinced that any changes below PortalExportControllerImpl will cause similar issues. 
> 
> My approach is to add a new StagingImpl.getRecentLayoutRevision which takes a Head attribute and returns the most recent layout revision where Head is true. Most of the code is duplicated from other parts of the portal. The new StagingImpl.getRecentLayoutRevisionId is the same as the one [without head](StagingImpl.getRecentLayoutRevisionId) except it uses fetchLayoutRevision(layoutSetBranchId, layoutBranchId, head, plid). 
> 
> In the PortletExportControllerImpl I needed to add a way to get the User and LayoutSetBranch. This code is copied from [LayoutStagingHandler._getLayoutRevision](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/model/LayoutStagingHandler.java#L143-L256) and then I edited out what I believe is irrelevant code.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@joshuacords 

1) throwing exceptions without any error messages should happen, in many cases these cause the support and gs teams to struggle to understand what's the root cause of a problem when it happens.
2) I'm almost certain the PortletExportController should not contain this logic for different reasons: 
a) I think if it's layout related we should be also applying fixes to the LayoutExportController too 
b) from an ExportController perspective we are handling layouts, and not layout revisions. That process should be agnostic to if we are publishing simple layouts or in a page versioning environment. When asking for layouts the advices should return the proper ids and stuff and the controllers from that on do not care if it's a layout or a layout revision.

**Comment by joshuacords** [comment]
Resubmitted here: https://github.com/matethurzo/liferay-portal/pull/2036

**Pull request closed without merging**
