### PR TITLE
LPS-67872 Don't try to delete latest file version if it's a PWC

### PR DESCRIPTION
**Pull request by giros**
Development of integration test is in progress

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54461. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by giros** [comment]
ci:stop

**Pull request closed without merging**
