### PR TITLE
LPS-88889 must add reference with missing=true parameter

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68212. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
