### PR TITLE
Lps 69254 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46179. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46292. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46329. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
