### PR TITLE
LPS-56308

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @matethurzo ,

After talking with @almonwork, he told me that for master, Index issues of Staging will be carried on Index side, but at the moment a solution for 6.2.x was necessary to be implemented.

I have implemented the solution to 6.2.x at https://github.com/matethurzo/liferay-portal-ee/pull/146 but as this LPS is reproduced at master, to avoid problems I think we should commit solution at both sides (master and 6.2.x) as we had some problems with 6.2.x pull request that are not commited to master.

Thank you

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo , @almonwork

https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/15755325

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo , @almonwork

About master changes, I have done today some additional testing and I have realized that there are some differences at Staging Indexation logic between 6.2.x and master, that affects to this LPS, please review following post:
  - https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/15755325

Thank you

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Did you review my post at: https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/15755325 about this LPS?

Thank you

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about this LPS-56308 and about my post at https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/15755325

Thank you!

**Comment by jorgediaz-lr** [comment]
Closing this pull request as explained at https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/15755325 solution to staging index problem at master are addressed with LPS-56593
This LPS must be commited to 6.2.x as LPS-56593 is only applied to master

**Pull request closed without merging**
