### PR TITLE
LPS-81744 export templates search

### PR DESCRIPTION
**Pull request by palius**

### CODE REVIEW

**Comment by palius** [comment]
ci:test

**Comment by palius** [comment]
ci:stop

**Comment by peterborkuti** [comment]
It was tested in https://github.com/palius/liferay-portal/pull/17

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60353. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e86dcd000f62~1...e86dcd000f62) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
