### PR TITLE
LPS-74081

### PR DESCRIPTION
**Pull request by giros**
Hi @matethurzo,

Please review. See my continuous comments on [LPS-74081](https://issues.liferay.com/browse/LPS-74081).

It's basically a revert of the changes of [LPS-53439](https://issues.liferay.com/browse/LPS-53439) which causes the issue. I wrote an explanation about why I think we can do the revert in a [comment](https://issues.liferay.com/browse/LPS-53439?focusedCommentId=1160048&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1160048). 

Let me know if you have any questions.

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@giros please check if this has any implications for customers who already upgraded from the verify perspective

**Comment by giros** [comment]
@matethurzo As we discussed, reverting the Verify method should not cause problems for customers who have executed it earlier, because the behaviour change is only affecting future LAR export/imports.

**Comment by giros** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52451. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
