### PR TITLE
LPS-62844

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35629. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35701. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/4a115ec~1...4a115ec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
