### PR TITLE
LPS-81559 export screen - public layout should be displayed by default

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Máté,

This was easy and I talked about it to Péter, so no need for him to review it.

Thank you
Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by peterborkuti** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59923. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
