### PR TITLE
LPS-68827

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Mate
Could you help to review this pull request as high priority since one Japan customer is waiting for this fix?
The customer is going to go live by end of Oct
Thanks,
Dale

**Comment by daledotshan** [comment]
Information from Hai

The root issue is that we don't set right ownerId when import portlet to targetSite. Please refer to the below explanation.

In site's control panel, we can define portlet's configuration. When save MB portlet configuration, it will save this portletpreferences as ownerId=groupId, ownerType=2, plid=0, portletId=serviceName("com.liferay.message.boards"), the logic is SettingsConfigurationAction.getSettings()

Export process: we export this portlet's configuration by using exportService method, please refer to 
https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/controller/PortletExportController.java#L616-L649

Import process: we import it in this fix, due to we don't set right ownerId, so it won't add right portletpreferences for target so that the configuration can't take effect.

By the way, could you please take this as high priority? Because the customer plan to publish their site to live soon.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44143. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
