### PR TITLE
[Technical Support] LPS-76116 Making the LAR database agnostic for Timestamp types

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-76116

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @rodrigopaulino the code looks good, but I'm curious why didn't you use the XStreamConverter API in the portal similar to the FileEntryConverter?

Can you please rewrite to use that?

**Comment by rodrigopaulino** [comment]
Hi, @matethurzo!

I did not use the API at first because I wasn't sure that I could use BaseXStreamConverter for single value converters. I thought BaseXStreamConverter was created for objects with other nested objects that needed to be converted.
Anyway, I rewrote the TimestampConverter to extend the API now.

Thanks a lot for your review and guidance.
See new PR at https://github.com/matethurzo/liferay-portal/pull/1873

**Pull request closed without merging**
