### PR TITLE
LPS-55972 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by akosthurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26956. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
