### PR TITLE
LPS-62328

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @bejondshao,

It seems to me that this change will break existing functionality. Does the dlReferencePattern Pattern match to the existing patterns as well? If not than the regular DL entries won't be matched and won't be referenced. Either we need to implement the new fix as a separate check or integrate the existing ones with the new one.

Thanks,

Máté

**Comment by bejondshao** [comment]
Hey matethurzo,

With our test, we can insert internal images external images. dlReferencePattern is a new pattern create by me. There's no existing patterns.

If we are on the same page, I can spearate the check later.

Thanks
Bejond

**Comment by matethurzo** [comment]
Hey @bejondshao 

the question is not really the external images. If you check the code the code will match to these strings: "/c/document_library/get_file?", "/documents/", "/image/image_gallery?".

Does the new code match to these as well? I think the regex is just matching on the external images.

Thanks,

Máté

**Comment by bejondshao** [comment]
Hey @matethurzo ,

After Dale's SF commit, the pattern is going to match the url in src="url", besides, the pattern will discard the url which starts with "http://" or "https://". So then all "internal" urls are matched and will be checked. So "/c/document_library/get_file?", "/documents/", "/image/image_gallery?" will be matched.

**Comment by bejondshao** [comment]
Hey @matethurzo , are you on this now?

**Pull request closed without merging**
