### PR TITLE
[TECHNICAL-SUPPORT] LPS-62440 DDL records are not exported/imported with the DDL Display portlet

### PR DESCRIPTION
**Pull request by moltam89**
Hey @matethurzo , @marcellustavares ,

this is the continuation of LPS-62440, I extended the fix with some basic test cases.

I don't really like that the two tests file have very similar logic, but I couldn't find a better solution.
Let me know if you have any ideas.

Thanks,
Tamás

### CODE REVIEW

**Comment by marcellustavares** [comment]
Very cool @moltam89! Thanks for the tests!

**Comment by marcellustavares** [comment]
cc @vicnate5

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by moltam89** [comment]
Rebased and resent here:
https://github.com/matethurzo/liferay-portal/pull/1509

**Pull request closed without merging**
