### PR TITLE
LPS-53343 Export/import the default values web content of the web content structures

### PR DESCRIPTION
**Pull request by zsigmondrab**

### CODE REVIEW

**Comment by dacousalr** [comment]
Hi Zsigmond,

I have tested it in the case of some DDMStructures with deafult values but without JournalArticles. DDMStructures and their default values are exported but only DDMStructures (without their default values) are imported.

Regards

**Comment by zsigmondrab** [comment]
Hi @matethurzo, @dacousalr,

I fixed the second usecase also according to talk with Máté.

Regards,
Zsigmond

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/24419

**Pull request closed without merging**
