### PR TITLE
[TECHNICAL-SUPPORT] LPS-78908

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @wanderlast

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by matethurzo** [comment]
@jonathanmccann @wanderlast I'll take a look despite the failing tests. I don't think those are related

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56655. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@wanderlast looks great, thanks

**Pull request closed without merging**
