### PR TITLE
export-import-ui

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33658. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/f6f2b4a~5...f6f2b4a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
