### PR TITLE
LPS-56413

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27781. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/ef80c12~5...ef80c12) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27823. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/9f091eb~9...9f091eb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
