### PR TITLE
LPS-73213 Staged Groups parent relations should be consistent on staging activation, deactivation and group update

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
cc . @dcousalr

Hey @matethurzo 

When do you think you'll have time to check this?

We need to assert that this is the expected behavior in order to move forward and provide a fix to the customer

Thanks in advance!

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @matethurzo, 

Any update on this?

Thanks!

**Comment by matethurzo** [comment]
hey @robertoDiaz I've talked to @zsigmondrab regarding this I thought it reached you. I checked the pull and basically the StagingImpl.isGroupAccessible() is describing how groups should see each other and this logic should be applied in this pull as well.

please check this pull and resend with the updated logic and let me know if you have any other questions

**Comment by zsigmondrab** [comment]
@dacousalr

**Comment by robertoDiaz** [comment]
The problem here is that we have this code in [com.liferay.portlet.exportimport.service.impl.StagingLocalServiceImpl#addStagingGroup](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/exportimport/service/impl/StagingLocalServiceImpl.java#L593) method:


```
if (liveGroup.getParentGroupId() !=
				GroupConstants.DEFAULT_PARENT_GROUP_ID) {

                        Group parentGroup = liveGroup.getParentGroup();

			if (parentGroup.hasStagingGroup()) {
				parentGroup = parentGroup.getStagingGroup();
			}

			parentGroupId = parentGroup.getGroupId();
		}
```

			

If I've understand you well, it should also follow the StagingImpl.isGroupAccessible() clause using the stagedParentGroup as group and the liveGroup as fromGroup, like this:

```
if (liveGroup.getParentGroupId() !=
				GroupConstants.DEFAULT_PARENT_GROUP_ID) {

			Group parentGroup = liveGroup.getParentGroup();

			if (parentGroup.hasStagingGroup()) {

				Group stagingParentGroup = parentGroup.getStagingGroup();

				if (StagingUtil.isGroupAccessible(
					stagingParentGroup, liveGroup)) {

					parentGroup = stagingParentGroup;
				}
			}

			parentGroupId = parentGroup.getGroupId();
		}
```

In this case the parentGroup of the stagedGroup will always be the liveGroup parentGroup.

Is it right?

**Comment by robertoDiaz** [comment]
Hi @matethurzo , @zsigmondrab 

Any update related with the doubt from the previous comment.

**Comment by almonwork** [comment]
Hi @matethurzo @zsigmondrab 

To separate the inteded behaviour from the actual implementation, we need clarification of the expected behaviour.

So

> In this case the parentGroup of the stagedGroup will always be the liveGroup parentGroup. Is it right?

This seems to be the key question. Based on this, code might need to be changed (o not) to reflect this. We (Spain) may develop the necessary changes to reflect the desired behaviour.

This issue is quite important, as it affecting a customer while negotiating DXP upgrades. Please, consider it urgently.

Thanks
  Alberto

**Comment by zsigmondrab** [comment]
Hi @robertoDiaz,

waiting for @matethurzo, I have taken a look at your modification and if I'm right, using those groups as parameters, it doesn't implement the right behavior.

The proposed modification in the com.liferay.portlet.exportimport.service.impl.StagingLocalServiceImpl#addStagingGroup method is assigning the parent's stage group to the child group as parent group if the isGroupAccessible is true for the parent's stage group. However, it should do that only if the isGroupAccessible is false for the parent's live group which stands in case of remote staging. It's because a staging group can be a parent group only, if the live group isn't accessible (in case of remote staging, for example). The live group is the parent otherwise.

So I think, the correct way could be to use the parent live group and the child live group as parameters for isGroupAccessible in this order, but the conditions should be negated in that case also.

				if (!StagingUtil.isGroupAccessible(
					liveParentGroup, liveGroup)) {

					parentGroup = stagingParentGroup;
				}

In addition, the child stage group which is just being created should get the same parent.

Does it make sense with having the goal in mind? Let me know if I missed or misunderstood anything.

Thanks,
Zsigmond

**Pull request closed without merging**
