### PR TITLE
LPS-87741

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
cc @giros

**Comment by danielkocsis** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65849. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65858. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
