### PR TITLE
LPS-90112 Improve the performance of the SystemEventVerifyProcess

### PR DESCRIPTION
**Pull request by achaparro**
Hi @matethurzo,

We have detected performance issues with the process SystemEventVerifyProcess during the upgrade. For example with 400000 groups with no staging this process takes 15 hours in DB2. We have modified the logic to only process live groups, the execution took 1 second after this change.

Could you review if everything is ok regarding my changes?

Thanks.

cc/ @jorgediaz-lr

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
hey @achaparro staging suite reported test failures that seem relevant, can you check them please?

**Comment by achaparro** [comment]
Hey @matethurzo,

I have tried to figure out how this errors are related to the pull since hte changes seem unrelated and I have realized that we can the same errors in other pulls like this:
https://github.com/brianchandotcom/liferay-portal/pull/67641#issuecomment-460982694

Please, execute ci:test:staging in one of your pulls to verify it.

Taking this into account I will proceed to reopen the pull.

Thanks.

**Comment by achaparro** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67878. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
