### PR TITLE
LPS-76613 Avoid link-to-layout type export/import content processing for entities where it's unnecessary

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-76613

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by giros** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54153. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c36dab5703c2~1...c36dab5703c2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54189. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/4a0f4c368061~2...4a0f4c368061) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
