### PR TITLE
LPS-56010

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @jgok

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @jgok,

I was testing the LPS for the bug, but when I click the manage site pages variations, the pop-up is shown but the contents of the pop-up is blank.

I guess based on the LPS this is not what you are trying to fix right?

Thanks,

Máté

**Comment by jgok** [comment]
Hi @matethurzo ,

I was able to create a site variation from the front-end on the Staging toolbar. 

LPS-56010 is that after a site variation is created, it is not possible to change between site variations.

Thanks,
Josh

**Comment by jgok** [comment]
@matethurzo , any update on this?

**Comment by matethurzo** [comment]
I wanted to test it before merging it, but I wasn't able to do so due to a different error in master. I'll re-try and will review the changes.

Thanks,

Máté

**Comment by matethurzo** [comment]
Hey @jgok 

We have been refactoring the master's control panel a bit, and the steps in the ticket won't be possible to reproduce from now on.

Can you please send this to me on 6.2.x and I'll test and review it there, sine I assume it is a problem in 6.2.x too.

Thanks,

Máté

**Comment by matethurzo** [comment]
In the meantime I went ahead and applied it to 6.2.x: https://github.com/brianchandotcom/liferay-portal-ee/compare/a40f5f6fda...8abea0167d

Brian also merged it in. Thank you!

**Pull request closed without merging**
