### PR TITLE
LPS-81718

### PR DESCRIPTION
**Pull request by dacousalr**
\cc @ealonso

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:reopen

**Comment by dacousalr** [comment]
ci:retest

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60349. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/8d2840fcd04e~3...8d2840fcd04e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
