### PR TITLE
LPS-56577

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
@matethurzo 

I do have a concern about this pr as it left one problem.

Before publishing from staged site to live site, the live site already has some default roles like Administrator, Owner, Power User, etc.

For those roles, they have no ideas about the uuid of those from staged site. So the uuid for those roles are different between staged site and live site.

So the fix won't work for them as it only set uuid for newly created role by publishing.

I wonder if we can force them to have same uuid by code

```
if (role != null) {
  role.setUuid(uuid);
  return role;
}
```

By doing this, one thing I can see it will break is that if somewhere the old uuid is referenced, this will be a problem.

Any ideas?

Thanks
John.

**Comment by zxdgoal** [comment]
@matethurzo 

Bump

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27816. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/aaecf05~1...aaecf05) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
