### PR TITLE
LPS-55020

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi Máté,

The root cause of the **PermissionChecker not initialized** error reported at this LPS it seems to have other root cause (some thread issues that i am investigating related with LPS-54672)

But we are throwing this exceptions at log because we are using the TrashHandler class instead delegating the trash checks to the isTrash / isTrashContainer methods.

With this modifications we avoid manage the exceptions that TrashHandler throws and simplify all the code.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25776. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
