### PR TITLE
LPS-82289 JournalArticle modelListener handles JournalArticleResources as well

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60415. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/1dca45703b19~4...1dca45703b19) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
