### PR TITLE
LPS-54744 Pr/19

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
@matethurzo 

let me know if i missed anything or if I should make any more changes.

Thanks!
Andrew

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @arbetts,

There are lots of rebase conflicts because the layouts admin portlet is being modularized, can you please rebase it and push it up again?

I'll review it right away after that!

Thanks,

Máté

**Comment by arbetts** [comment]
https://github.com/matethurzo/liferay-portal/pull/1024

**Pull request closed without merging**
