### PR TITLE
Lps 82439 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by akosthurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60356. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60363. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/37bc05af3c2a~2...37bc05af3c2a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
