### PR TITLE
LPS-71131 SF

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/665. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/92be4a698d60~1...92be4a698d60) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50048. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/65d90988220a~1...65d90988220a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50088. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/5552a6f565c3~2...5552a6f565c3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50097. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e7329a8f11f5~2...e7329a8f11f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50100. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/6b6f632a12bd~2...6b6f632a12bd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
