### PR TITLE
LPS-56545

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Forward port of  LPS-49184+LPS-55612, see original pulls:
    - **LPS-49184:** https://github.com/brianchandotcom/liferay-portal-ee/pull/9081 and https://github.com/brianchandotcom/liferay-portal-ee/pull/9154 (partial)
    - **LPS-55612:** https://github.com/brianchandotcom/liferay-portal-ee/pull/10113

We must avoid unnecessary updates of DDMStructures as it triggers a reindex of all its asociated JournalArticle.
*Note:* at master reindex code of JournalArticle for DDMStructure is not implemented yet as explained at LPS-50379 and LPS-53512, so I have not forwardport that part.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
SF problems seem was solved and test errors are from other LPS

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Rebase to last master

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Fixed SF error after rebasing to last master

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Fixed SF error after rebasing to last master

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Rebase

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
@matethurzo I will be on holiday for three weeks, I will return the *August 10*

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29361. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/fbd1611~2...fbd1611) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
