### PR TITLE
LPS-70830 Portlet permissions are not imported from LAR, even though the exported LAR had the Export Permissions option toggled

### PR DESCRIPTION
**Pull request by arboliveira**
Hi Máté! I'm forwarding you this fix for a `jp-support` ticket that we identified as really pertaining to Export/Import. Please consider @linolaoj's comments from his original pull to me. (https://github.com/arboliveira/liferay-portal/pull/232#issue-212193136) I only gave a cursory look at the code, but didn't actually review it; this seems to be your area of expertise :smile: Thank you!

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @linolaoj,

I saw your comment on the PortletDataContextImpl changes, but it's allowed to modify the kernel, what's not allowed to make breaking changes. The PDC is provider type also which gives you more flexibility.
This way of casting the objects is not the best solution as you pointed out as well.

But before that actually, I'm not sure if this is the best solution. Why are we defaulting the permissions to true if it's not present? for me it seems more that the value is not propagating properly from the UI, default to true is a big change in the logic.

**Comment by linolaoj** [comment]
Hi @matethurzo,
Thank you for looking at this. 
I'll try to make another fix avoiding the cast.
Regarding defaulting the permissions, some portlets have on the export UI the option to include permissions but don't have this option on the import UI. That is why I setting the default to true. Do you think it is best if I make a separated fix for each portlet UI?  

Thanks!

**Comment by matethurzo** [comment]
@linolaoj those screens should be pretty much the same, the same code is controlling that. can you tell me which did not have and which did? I can look into it deeper.

**Comment by linolaoj** [comment]
@matethurzo, here are a few that I found:

- Have permission option for export and import:
Blogs
Bookmarks
Calendar
Documents and Media
Page Comments
Wiki

- Have permission option just for export:
Activities
Alerts
Asset Publisher
Blogs Aggregator
Breadcrumb
Categories Navigation
Members
My Sites
Search

- Don't have permission option:
Form
Dynamic Data Lists Display
Polls Display
Web Content Display

I can send you a more complete list if it helps.
Thanks!

**Comment by linolaoj** [comment]
new pull https://github.com/matethurzo/liferay-portal/pull/1641

**Pull request closed without merging**
