### PR TITLE
[TECHNICAL SUPPORT] LPS-88018

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-88018

Moving `staging.delete.temp.lar.on.failure/success` properties to system settings is important for better staging support:
 - Now, in case of any staging issue you have to restart your application server in order to apply them.
 - This change and restart normally cannot be done inmediatly and it is necessary to wait to next scheduled reboot.

/cc: @moltam89

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about this PR?

Thank you

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

There was a conflict with _BREAKING_CHANGES.markdown_ file.

I have rebased this pr to last master

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

After rebasing my changes, now all tests have passed correctly.

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

Do you have any update about this pr?

Moving `staging.delete.temp.lar.on.failure/success` properties to system settings is important for Spanish support team in order to get better staging support:
 - Now, in case of any staging issue you have to restart your application server in order to apply them.
 - This change and restart normally cannot be done inmediatly and it is necessary to wait to next scheduled reboot.

Thank you

/cc: @moltam89 can you also have a look to this change and talk with Máté?

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66868. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Thank you @matethurzo!!

**Pull request closed without merging**
