### PR TITLE
LPS-80295 JournalExportImportTest modified to fit the recent friendlyUrl changes

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59374. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/eb0bfffc8322~6...eb0bfffc8322) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59397. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3988ff9637e0~8...3988ff9637e0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59442. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a0582b52c815~8...a0582b52c815) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59649. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/abb30240fbf5~14...abb30240fbf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59650. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
