### PR TITLE
[TECHNICAL-SUPPORT] LPS-54744

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @matethurzo, this is an update for [LPS-54744](https://issues.liferay.com/browse/LPS-54744).

Thanks!

@arbetts

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by arbetts** [comment]
@matethurzo 

I had to rebase this once already (and you did once too) so is there a way we can get this reviewed before we would need to rebase again?

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @arbetts haven't we merged this in already?

Anyway I tried to rebase it and it was failing again, sorry for that, can you please rebase it once more? Please send it to @danielkocsis this time, he'll take care of the review.

Thanks again!

**Pull request closed without merging**
