### PR TITLE
LPS-53858 After enabling local live staging, non-staged portlets cannot view their own dynamic data mapping structures

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Máté,

the passed scopeGroupIds solves the original problem. I think, the DDMStructure should not be handled as a staged portlet ever and should based on the staging status of the portlet to which they are connection on data level. With this scopeGroupId passing the DDMStructure handling will happen on the right group.

However, this caused an other problem that the Add button cannot be seen on the DDMStructure view popup opened from the WC, DM or DDL view. To solve this second problem I removed the staging permission checking from the DDMPermission class. As I think, the DDMStructure should not ever be staged, it's not necessary to use the stage permission check.

I may have removed the complete class as it doesn't make that much sense to have that without the removed code, however, it's more convenient solution from our perspective.

Update: if the modifications are fine, then this should be sent to @marcellustavares, I think.

@ssmith353

I tried to test all of the cases but please help me to find problems if there is any with testing this again carefully. I really hope this will be fine for now, however, it has several aspects. I know that there is problem with "Metadata Sets". According to my tests, those will be staged at switching the staging on for Document & Media portlet only if there is any "Document Type" to which the "Metadata Set" is connected. It's an other issue then the original one, seems to be completely independent from that one and can be handled separately. Let me know if you need my help at that one also.

Thank you,
Zsigmond

### CODE REVIEW

**Comment by ssmith353** [comment]
Hey @zsigmondrab,

I'm testing this just after  61e0705f59e08a1b3a4bc42e3718bc8a10139d75, I have applied the changes to  DDMPermission, and the toolbar.jsp's. It all looks good! But one side effect of removing the DDMStructure permissions is whenever you disable staging, the DDMStructures associated with that groupId are left orphaned in the database.

**Comment by zsigmondrab** [comment]
Hi @ssmith353,

do you mean when a portlet is staged and the DDMStructure is being created to the staging group?

If so, I guess, you had published them once before you switched the staging off? May be a stupid question, just to clarify.

The problem coming only fit the fix, I guess...

Thank you,
Zsigmond

**Comment by ssmith353** [comment]
Hey @zsigmondrab,
This might actually be an issue that was present before, in DDLPortletDataHandler.java, doDeleteData only contains the records, not the structures. So when DDL is staged, and you disabling staging, it orphans the data. Whereas in JournalPortletDataHandler.java it also removes the structures upon disable.

**Comment by zsigmondrab** [comment]
Hi @ssmith353 ,

is that independent of the current fix then? Or is that possible that was a hidden issue?

I'm asking these because I'll able to deal with it tomorrow only and answering these might make the process faster. You may have deal with that also in the meantime if you have any free time.

Of course, if it's a regression, I'll definitely deal with that.

Thank you in advance,
Zsigmond

**Comment by ssmith353** [comment]
@zsigmondrab,

Looks like it's independent, and it was revealed by fixing this. I'll send a separate pull for that issue. 

Thanks for all your help Zsigmond! 

-Steven

**Comment by zsigmondrab** [comment]
@ssmith353,

you're welcome. Let me know if I can help at anything.

Zsigmond

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/433. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
