### PR TITLE
LPS-81950 Check existing layout on remote live

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
Tests passed locally.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60504. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/zoltancsaszi/liferay-portal/pull/8. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
