### PR TITLE
LPS-77882 Create backend infrastructure for staging warning messages

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-77882

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by giros** [comment]
Unrelated errors.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
