### PR TITLE
LPS-76420 buildLang

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
ci:reopen

**Comment by zoltancsaszi** [comment]
Tests passed locally.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60993. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/51689ee71774~4...51689ee71774) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60994. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/4bc6e172f4ca~5...4bc6e172f4ca) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
