### PR TITLE
LPS-60792 adding resetPortletScope to Archived setup

### PR DESCRIPTION
**Pull request by balazssk**
Hi Mate,
Based on [Brian's comment](https://github.com/brianchandotcom/liferay-portal/pull/53834#issuecomment-353434462) I'm splitting the commit.

This one should go in first. The second commit, I'll send to the com-liferay-layout subrepo.

Can you please have a look at this?

Thanks

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @matethurzo ,
Can you please have a look at this and forward if it is ok?
Thanks.

**Comment by balazssk** [comment]
Hi @matethurzo ,
Can you please have a look at this and forward if it is ok?
Thanks.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54351. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
