### PR TITLE
LPS-76668

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-76668

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
hey @holatuwol this code change break tests in the staging suite and those seem legitimate errors, can you please check them? thx

**Pull request closed without merging**
