### PR TITLE
LPS-79000 former web-experience remains removed

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
Reason:
https://github.com/brianchandotcom/liferay-portal/pull/58741#issuecomment-392130415

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59147. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
