### PR TITLE
[TECHNICAL-SUPPORT] LPS-78908

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian @wanderlast

### CODE REVIEW

**Comment by jonathanmccann** [comment]
From @wanderlast:

>My reason for using the deprecated methods was primarily due to the time and effort that would be required for an alternative fix versus the current state of the WYSIWYG portlet.

>The WYSIWYG Portlet is theoretically only supposed to be used when the "full capabilities of Liferay's CMS system is not needed" and therefore doesn't really have any actual staging infrastructure within Liferay itself. Its content is stored and retrieved in its portlet preferences and everything else goes through the base/default classes. This means that following the normal import/export processes that other portlets use would require quite a few extra classes be written which is admittedly an outcome I wanted to avoid. This is especially in light of the fact that the WYSIWYG portlet is considered to be in its 'final version'. While we still do support it until its EOL (and I would judge this current behavior to be a bug), I'm not sure how valuable it'd be for me to implement most of the staging infrastructure for a portlet that is reaching its EOL.

>Speaking more specifically about the method I used, most portlets, if not all, use an "ExportImportContentProcessor" for their processImportPortletPreferences method. Only if one can't be found does the code check for a portlet data handler and use the processImportPortletPreferences method in it. You can see this behavior at PortletImportControllerImpl from line 588-611, where the code would check to see if the WYSIWYG portlet has an ExportImportContentProcessor, find that it doesn't, and then go to the PortletDataHandler -> BasePortletDataHandler -> processImportPortletPreferences (which is the overriden deprecated method) -> doProcessImportPortletPreferences. The current solution in the PR simply substitutes the new WYSIWYGPortletDataHandler for BasePortletDataHandler. While I think it should be possible to create an ExportImportContentProcessor, it would have required extra work with regards to accounting for and writing code related to capabilities. This same logic applies to why I didn't use DLReferencesExportImportContentProcessor--WYSIWYG does not have a staged model and it would therefore require far more work to implement in comparison to the current fix.

>If you feel like one of the other classes I mentioned above would be a better fix, please let me know and I'll look into it further. Thanks!

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
Updated to resolve source formatting issue.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@wanderlast I don't quite understand the reasoning behind using the deprecated code pieces. There is no need to develop any staged models or create any additional orchestration, an implementation of the ExportImportPortletPreferencesProcessor is needed, nothing more.

This subframework is specifically created to deal with one specific task during the staging publication: processing the preferences. If the portlet does not have any content or any other related stuff, this could still work, as the Asset Publisher does not sport any staged models it still has a pref processor.
As you wrote the preference processor will be invoked by the framework you don't even need to do anything else just registering it as a component service with the proper portlet name.

Also implementing capabilities is an option, Bookmarks pref processor does not have a capability either.

**Pull request closed without merging**
