### PR TITLE
[Technical Support] LPS-60792 Copy the change of Web Content Display preference change in case of selecting Global web content

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Máté,

this scenario is a difference comparing that with the general data transition rule that 

"Important: Portlet data, related resources, and permissions on resources are only copied from a site template to a site when that site is first created based on the template. No changes made in a a template’s portlet data, related resources, or permissions are propagated to the site after the site is created. Neither are such changes propagated to a site by Reset or Reset and Propagate features."

and

"Only global portlet preferences or local portlet preferences which don’t refer to IDs are overwritten."

However, this may make me a bit confused we have a more clear description in one of our internal doc:

"changes in portlet preferences related to global contents are propagated from the site template to the site"

Resource: https://dev.liferay.com/discover/portal/-/knowledge_base/6-2/using-site-templates

Regards,
Zsigmond

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Máté,

The issue came from EE customer. Is it possible that you can review this with a higher priority?

Best Regards,
Hai

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @zsigmondrab @yuhai 

The portlet preferences processor should never modify the scope type, it is being set before a portlet is being imported and there is a more complex mechanism to set this.

Please see LayoutImportController.setPortletScope() method. Can you please investigate it and check that method why is it not setting the proper scope?

Thanks,

Máté

**Comment by zsigmondrab** [comment]
Hi Máté,

the problem is that the WCD portlet is a special one as the portlet scope can be different from the data scope that it shows. There is no other portlet like this. Because of that, I thought it is better to keep that logic within the portlet specific logic, as I could not find that right way to do that. Actually I do not now it the framework has been prepared for such a cases.

Any specific idea?

Thank you,
Zsigmond

**Comment by yuhai** [comment]
Hi Máté,

The fix uses(pretend/fake) portlet scope concept to solve the issue, because the case(WCD) only displays global content by choosing article (not change portlet scope).

Please refer to the detailed explanation from https://github.com/daledotshan/liferay-portal/pull/348#issue-119128314

Thanks,
Hai

**Comment by matethurzo** [comment]
Thanks for the supplied information, please let me investigate the options we have for this.

**Comment by yuhai** [comment]
Hi Máté,

Hope you are doing well. I understand that you might be busy with different tasks, I would like to just quickly follow up with you about this pull request. At the moment we would like to move forward with the case and wondering if you have had any update available for us?

Best Regards,
Hai

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33310. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/0c6d68e~1...0c6d68e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi Máté,

Thanks for working on the pull request.

I see your changes. I find your change will remove the fix function because the change will revert the fix. Back to PortletImportController.updatePortletPreferences) { scopeType.equals("company")=false // 1314 line}. Because in the case, we don't set WCD's  portletpreference and its previousScopeType = empty.

I find after import every portlets, we will reset PortletScope in PortletImportController.doImportFile(){ 
finally {
	_portletImportController.resetPortletScope(
      portletDataContext, portletPreferencesGroupId);
}
// 805 line}

And when import every portlet, we also will use the real portletscope in 	PortletImportController.doImportFile() {setPortletScope(portletDataContext, portletElement); //746 line}

So the faked portletScope won't affect other places when import next portlet. I don't make sure whether I understand your change purpose. Please help check this point.

Best Regards,
Hai

**Comment by zsigmondrab** [comment]
Hi Hai,

Máté is right in the way that if we change something at some place in the context that contains information for the broader logic also, it is strongly recommended to return with the same place after the current unit did its job.

It is possible changing the scope there does not have effect for now, however, the code outside of the current method can be changed any time also and the scope should have the expected value there.

I should have thought of that also at review.

Does that change cause any problem at the fix?

Regards,
Zsigmond

**Comment by yuhai** [comment]
Hi Zsigmond,

Yes, the change will remove the previous fix.

Due to the change occured in same method, the previous set scope "company" will be reset for "empty" for the current case(because previousScopeType is empty). Please see https://github.com/matethurzo/liferay-portal/compare/0c6d68e~1...0c6d68e

For the current case, we need to still keep the scope "company" after the method execute finished.

Regards,
Hai

**Pull request closed without merging**
