### PR TITLE
LPS-60134 Pages cannot be reordered unless every page in the site is published

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
cc/ @zsoltbalogh

**Comment by zsoltbalogh** [comment]
@matethurzo, I'll post my assessment of this fix on the ticket by Monday the latest.

**Comment by zsoltbalogh** [comment]
Please close this PR, it shouldn't be merged, see https://issues.liferay.com/browse/LPS-60134?focusedCommentId=1730187&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1730187

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69348. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69350. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a8369900e1d9~1...a8369900e1d9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
