### PR TITLE
LPS-62681 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @matethurzo, could you please double check this fix. I'm not sure if that's how we should fix it.

groupId/structureKey works like a PK and the conflict eventually will happen during import but I tend to think we should really fail. Because the customer code might be referencing structureKey for querying, etc.

What do you think?

cc @danielkocsis

Regards,

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Máté and @marcellustavares

I want to explain the fix. The fix refers to brianchandotcom#18714.

When same structureKey existed in targetSite and they are not same structure, we should force imported structure generate new structureKey.

And the issue can be reproduced on clean master without custom code. So I think the issue should be fixed. Please refer to LPS-62681's description.

By the way, the issue came from EE customer.

Regards,
Hai

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35641. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2b8d2d8~1...2b8d2d8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @yuhai @marcellustavares,

I think the fix is proper, I've only added an explanation comment, since I think it might be confusing what's going on. Otherwise I think it's fine.

Thanks!

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35691. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/052d5b2~1...052d5b2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
