### PR TITLE
[TECHNICAL-SUPPORT] LPS-73526

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPS-73526
https://issues.liferay.com/browse/LPP-25980

Sending this directly to you because the normal TSE reviewers are out of the office.

The client is experiencing an issue where a platform-dependent timeout for accessing the remote live server with remote staging is causing their staging server to become unusable when the live server is down (their timeout is long enough that it triggers their proxy server's timeout, so they can't load pages).

The problem is only for admins and not guest users, because guest users viewing a public staging site do not trigger any access to the remote live site (whereas admins have two buttons that access it -- "Go to Remote Live" and "Remote Live" -- meaning the platform-dependent timeout length is reached twice before the page loads).

I think the easiest way to solve it (and least likely way to introduce regressions/behavior changes for other clients on DXP) is to introduce a new portal property that adds the option to introduce this timeout. That way we don't have to commit to a default value necessarily, but instead recommend a reasonable value be set for if and when the remote server goes down. I've tested this using an EC2 instance that experiences the long timeouts.

Please let me know if there are any concerns or alternative suggestions. Thank you.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:reopen

**Comment by Alec-Shay** [comment]
ci:retest

**Comment by Alec-Shay** [comment]
Hello @matethurzo,

Will you be able to take a look at this soon? It's been a few days, and although it's not a critical issue, I'd like to be able to have at least some update for the waiting client.

Thanks!

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/451. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Alec-Shay** [comment]
Thanks!

**Pull request closed without merging**
