### PR TITLE
LPS-67467 Autogenerated

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @matethurzo,

Could you take a look at some of these commits? There's no need to review the whole PR (@sergiogonzalez has already done that), but there are a bunch of changes related to Staging that I'm not sure if are correct.

In ec74ffef81783283d9aea07afb0ae23255a8a995 I implemented a SMDH for a new model (FriendlURL) that has a relation with BlogsEntry that doesn't fit very well in any of the supported kinds of relations. We talked about this a while ago, and you recommended me to import/export these manually, as done for LayoutFriendlyURL.

As FriendlyURL are exported as references, the infrastructure tries to import them before handling the BlogsEntry; but as we need the BlogsEntry classPK to correctly import the FriendlyURL we have a chicken and egg problem here. To solve that, I changed the SMDH base class so that subclasses can customize which entities are handled explicitly and which ones are imported automatically. See
b1b20ff2e468e4b6bc6119593fd5cd60c2d0108b.

Finally, in 5e36cc97ab64d4537cbf744173bd85a69bbe11e2 and d6058aea8356bfcc3b62d698a23ac4ed8b48d42e I had to create a helper component and set the class loader so that XStream was able to load the FriendlyURLImpl. Not sure if there's a better approach for this.

And that's all. If you need more info or context on why things are this way, feel free to contact me.

Thanks!

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
first i was like :open_mouth: but then i realized no need to review everything :smile:

**Comment by adolfopa** [comment]
@matethurzo Did you check this PR? See anything wrong with changes?

**Comment by matethurzo** [comment]
Hey @adolfopa I was checking it, but hasn't completed it yet. I have some questions I'll add annotations in the code for them.

**Comment by adolfopa** [comment]
Ok, thanks @matethurzo!

**Comment by matethurzo** [comment]
@adolfopa closing this as we have discussed the details.

@sergiogonzalez

**Pull request closed without merging**
