### PR TITLE
LPS-81567 SF generated

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60046. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/31bc38ce4754~1...31bc38ce4754) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60129. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/22ff039d4f53~1...22ff039d4f53) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60135. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2f79a7b67343~2...2f79a7b67343) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60199. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/02934cf77777~1...02934cf77777) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
