### PR TITLE
LPS-67732

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/42770

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42804. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42832. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/448a95c~1...448a95c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
