### PR TITLE
LPS-87688 buildLang

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65694. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:retest:relevant:norebase

**Comment by zoltancsaszi** [comment]
ci:stop

**Pull request closed without merging**
