### PR TITLE
LPS-73910

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:reopen

**Comment by giros** [comment]
I finally managed to make an analysis of mass deletion as well. See my results at https://issues.liferay.com/browse/LPS-73910?focusedCommentId=1111155&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1111155

/cc @mhan810

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51576. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
