### PR TITLE
LPS-58408

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
cc/ @juliocamarero

**Comment by juliocamarero** [comment]
:+1:

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29918. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
