### PR TITLE
LPS-76311 fixing return statement

### PR DESCRIPTION
**Pull request by balazssk**
Hi @matethurzo ,
I'd like to make this change, can you please look it over?

Thanks,
Balazs

### CODE REVIEW

**Comment by balazssk** [comment]
hi @matethurzo ,
Can you please have a look at this?
Thanks

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53615. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
