### PR TITLE
LPS-80563 use pattern from aui BaseInputTag for remembering radio set…

### PR DESCRIPTION
**Pull request by palius**
…ting when refresh.

### CODE REVIEW

**Comment by palius** [comment]
ci:test

**Comment by peterborkuti** [comment]
ci:test

**Comment by peterborkuti** [comment]
ci:open

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58245. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/44669e74ec00~1...44669e74ec00) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
