### PR TITLE
LPS-70527 Initialize PortletDataContext with the company group mapping

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@matethurzo Could you please review this one? It's related to another PR I sent to DDM subrepo.

@marcellustavares @ehan

**Comment by leoadb** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48906. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
