### PR TITLE
[TECHNICAL-SUPPORT] LPS-57125

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Mate,

This is a rollback of one of your commits.
See https://github.com/jonathanmccann/liferay-portal/pull/768#issuecomment-124223305 for some more information.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Well, this was quite a while ago! :)

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28609. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
