### PR TITLE
LPS-88406

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test:sf

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66494. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66507. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
