### PR TITLE
LPS-67872

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@arthurchan35 I'm pretty sure this is not a proper change.

exporting and importing locks is a generic behavior of staging and this is a functionality.

on the other hand the LPS is specific to the DM component but the fix is changing the default behavior for all components related to staging not just DM. There might be several other implications that we need to consider when changing something like this.

please resend

**Pull request closed without merging**
