### PR TITLE
LPS-64780

### PR DESCRIPTION
**Pull request by LeventeHudak**

### CODE REVIEW

**Comment by LeventeHudak** [comment]
Based on https://github.com/brianchandotcom/liferay-portal/pull/38382. Only review after changes are in master.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38516. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/1b5feff~3...1b5feff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38538. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/0a320cb~4...0a320cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38568. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a8f6927~4...a8f6927) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
