### PR TITLE
LPS-59365 get selected group from request attribute to build a correct pages tree in staging mode enabled

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Mate, 

it seems this is a regression from your changes about the GroupDisplayContextHelper.

I don't really understand the solution. Actually, I would prefer to keep the call to the DisplayContext in the jsp and have the logic in the java side, but I am not sure if this change is the right thing to do.

Can you please have a look and let us know what you think? 

thank you!

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31099. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
I'm currently investigating the issue. It seems like you are right this is not the right solution, a wrong group id is being passed in the request, that's why this is a bug. I'll keep on looking.

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31479. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/7e9775e~4...7e9775e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @juliocamarero,

we have ended up fixing this in the DisplayContent the bug was there we always got the live group id. We have actually found one other bug too, that's also included.

Thanks!

**Comment by juliocamarero** [comment]
Awesome!

**Pull request closed without merging**
