### PR TITLE
LPS-75655 staging bar new design

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Máté,

This needs some backend modification to fix the original issue.

Thank you
Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by peterborkuti** [comment]
Failure seems to me not related, page creation without staging.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60962. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
