### PR TITLE
LPS-79439 Popover tag for staging

### PR DESCRIPTION
**Pull request by palius**
A fancy checkbox with popover.

### CODE REVIEW

**Comment by palius** [comment]
ci:test

**Comment by peterborkuti** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57183. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
ci:stop

**Pull request closed without merging**
