### PR TITLE
LPS-79066 language props fix

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by austinchiang** [comment]
@zoltancsaszi can you look into the branch conflicts? Thx!

**Comment by zoltancsaszi** [comment]
Hi @austinchiang,

@matethurzo hasn't reviewed it yet. He said we will discuss it.

**Comment by matethurzo** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/58627

**Pull request closed without merging**
