### PR TITLE
[TECHNICAL-SUPPORT] LPS-59894

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Preston-Crary

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @Preston-Crary if I understand correctly based on the ticket, the primary purpose of this change is performance improvement? To speed up how we are getting back the layouts right?

**Comment by Preston-Crary** [comment]
Hi @matethurzo,

at one point we were causing out of memory exceptions by making portlet preferences too large with all of the recent layout IDs being stored for each admin.  Someone fixed the issue by compressing that information into JSON inside the preferences.

This was the wrong fix since anytime we wanted to look up that information (layout branch ID, layout set ID, layout revision ID) we had to parse a table worth of information as a JSONArray.  Loading all of the layouts for a site in the control panel can get really expensive doing this - even if we paginate.

So I reverted that change 338c433, so the information was cached by the preference cache wrapper again (fixing the performance issue). But that brings back the memory issue. I fixed the memory issue by updating the logic to only store the information in the preferences when it is not the default (master) branch already 698cbaf.

This actually made the whole thing even slower since the preferences are very inefficient at storing changes.  So I updated PortalPreferencesImpl to skip storing when no change has been made 5a61e17.  This fixed the problem.

However, I did not like assuming that most of the branches would be the default because if that not true we would run out of memory again.  So I created the two new services / tables to store the information without ever needing to worry about the preferences getting too large again and improving performance of making changes (actual update, not deletions of things that do not exist) fixing any performance issue we could ever have with this in the future.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Thanks for the information, @Preston-Crary I'm reviewing the change. but it's quite big, I need some time to go through every change. Thanks!

**Comment by matethurzo** [comment]
hey @Preston-Crary the RecentLayout and RecentLayoutSet shouldn't be RecentLayoutBranch and RecentLayoutSetBranch respectively? It looks like you are managing those instead of layouts and layout sets. I didn't want to rename it without asking you.

**Comment by Preston-Crary** [comment]
Hi @matethurzo,

those would be a more precise names, except that the RecentLayout is both the Branch and Revision. We could separate the RecentLayout table into two tables (RecentLayoutBranch and RecentLayoutRevision) and it would make sense, I merged the two since they have everything in common but those two fields.

**Comment by matethurzo** [comment]
hey @Preston-Crary can you please split those two? I think it's two confusing and might causing problems later on. Thanks!

**Comment by Preston-Crary** [comment]
Okay, I'll split the services and rename them to: RecentLayoutBranch, RecentLayoutRevision, RecentLayoutSetBranch and resend the pull.

**Comment by Preston-Crary** [comment]
https://github.com/matethurzo/liferay-portal/pull/1244

**Pull request closed without merging**
