### PR TITLE
LPS-65096

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by danielkocsis** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38969. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/bb050db~1...bb050db) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
