### PR TITLE
LPS-71111 Use the proper property for the manual selection style

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47951. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
