### PR TITLE
LPS-55885 Moves export/import UI into a new portlet in the Site Administration

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hi Mate,

I've just send a pull request fixing a issue on top of it, see: https://github.com/matethurzo/liferay-portal/pull/1023

Could you make your changes on top of the new pull?

Regards,
Eudaldo

**Comment by matethurzo** [comment]
Sure, I'll review that instead

**Comment by ealonso** [comment]
Sorry for the inconveniences.

**Comment by matethurzo** [comment]
Closing this, as I'll review the other one

**Pull request closed without merging**
