### PR TITLE
LPS-88889 ReplaceExportImportContentReferences test added

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67875. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/547b70d02f2c~1...547b70d02f2c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
