### PR TITLE
LPS-79575 Show site pages variation selector even when current page is not enabled for the variation

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Hi @matethurzo, please take a look at this issue. I think that now it makes sense because we have no layouts tree anymore and there is no way to switch site pages variation when current page is not available in the active variation.

cc @ealonso

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57467. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
