### PR TITLE
LPS-78789 part 3 - checkbox tag

### PR DESCRIPTION
**Pull request by palius**
Hi,

Forwarding the new checkbox tag. :)

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by palius** [comment]
@matethurzo, @peterborkuti, I don't quite understand why is this PR closed. Should I submit another one?

**Comment by peterborkuti** [comment]
Hi @palius , no, it was closed by the testing framework.

**Comment by peterborkuti** [comment]
ci:reopen

**Comment by palius** [comment]
Thanks, @peterborkuti!

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by peterborkuti** [comment]
I am adding data-qa-id.

**Comment by peterborkuti** [comment]
Hi @palius , @matethurzo ,

Please, close this, I will add data-qa-id and will resend it. The modification has very small impact.

**Pull request closed without merging**
