### PR TITLE
LPS-88928

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by crodriguezy** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
hey @crodriguezy I've checked the code, but i'm not entirely sure what do we want to achieve with it. In both cases the exceptions being logged also being added to the session errors, which I presume will be processed on the UI, is there any specific reason we want to log them as well?

Also why do we need an error level if we send it to the UI?

**Comment by crodriguezy** [comment]
Hi @matethurzo, 
One of our customers is experiencing many problems with staging, one of them related with its activation in a particular site. We didn't know the reason until we added this code to a debug patch: no exception was logged at all. The user interface does not give much information about it, only "a nullpointer exception error has occurred", nothing else.

However, with this code, we could check the full stack trace of the error:

```
2019-01-09 17:27:44.875 DEBUG [http-apr-8080-exec-4][StagingConfigurationPortlet:147] java.lang.NullPointerException
java.lang.NullPointerException
	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:303)
	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:163)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
{...}
```
And we were able to solve the problem thanks to this extra information. I thought it would be very useful for diagnostic purposes in the future in case any customer experiences the same.

Let me know if now the reason is clearer :)

Thank you!

**Comment by matethurzo** [comment]
hi @crodriguezy thanks for the additional information, it is clearer now. I was assuming the UI displays some proper message.

I think in this case the proper solution first and foremost would be to provide a meaningful error message on the UI instead of just a NPE.
We had a mini project where we tried to identify different error messages and we provided error messages for them, but this seems like to be missed.
Do we know why we are getting the NPE at that point? That would help us decide what could be the error message

**Comment by crodriguezy** [comment]
Hi @matethurzo, in this case the error was related to this ticket: https://issues.liferay.com/browse/LPS-71136
You can see I rencently backported it to 7.0.x (still in review, https://issues.liferay.com/browse/BPR-21606), where I added an extra fallback case to fully fix it in 7.0.x. It is not needed neither in master nor in 7.1.x due to the (new) way the navigation is done when configuring the sites' preferences.

Anyway, besides the specific error in the user interface, it would be very useful for the support teams to get the full stacktrace in the logs, since it gives in most cases the final clue of the origin of any error that may occur.

**Comment by crodriguezy** [comment]
Hi @matethurzo , did you have the time to review my last comment? Does the PR looks good to you after the conversation?

Thank you!

**Comment by matethurzo** [comment]
thanks for the info @crodriguezy one last note, can it be a different log level? error seems to be a bit agressive

**Comment by matethurzo** [comment]
@crodriguezy thanks push it up when you are done with the extra commit, and i'll fetch it

**Pull request closed without merging**
