### PR TITLE
[TS] LPS-83223

### PR DESCRIPTION
**Pull request by yuhai**
Hi @matethurzo 

The PR extends from https://github.com/matethurzo/liferay-portal/pull/2193

Please refer to the fix explanation:

Commit 1 to 2:
The root issue is ChangesetPortlet property definition wrong. Please refer to https://github.com/liferay/liferay-portal/blob/master/definitions/liferay-portlet-app_7_1_0.dtd#L478-L485. For ChangesetPortlet, its preferences-unique-per-layout should false. Otherwise we will use same the data "com_liferay_exportimport_web_portlet_ChangesetPortlet created, with ownerId = 0, ownerType = 3, plid = 0" for different groups.

Other Commits:
The root issue is we treated the portlet com_liferay_document_library_web_portlet_DLPortlet as DataSiteLevelPortlets. However, it shouldn't belong to site level because the portlet can be placed in layout and it is instanceable portlet.

For test class DLAdminPortletDataHandlerTest, we removed isGetExportConfigurationControlsTested() method because other testcases (for example, BookmarksAdminPortletDataHandlerTest) doesn't include this method.

cc @arthurchan35

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevent

**Comment by yuhai** [comment]
Hi @arthurchan35, please solve the conflict files.

Hi @matethurzo, if you have free time, could you please check if our fix way is right (please refer to the 
 explanations from https://github.com/matethurzo/liferay-portal/pull/2199#issue-202798956)? After we solved the conflict files, we will resubmit it. 

Thanks, Hai

**Comment by arthurchan35** [comment]
Seems like someone also updated the test file yesterday, will resolve the confilicts

**Comment by arthurchan35** [comment]
ci:close

**Comment by arthurchan35** [comment]
https://github.com/matethurzo/liferay-portal/pull/2203

**Pull request closed without merging**
