### PR TITLE
LPS-91122 | Remove jQuery from the export-import modules

### PR DESCRIPTION
**Pull request by markocikos**
Hi Máté,

Please review the code.

Thank you!

### CODE REVIEW

**Comment by matethurzo** [comment]
hey @markocikos the code looks good, but why are we doing this? I haven't heard anything about this so far

**Comment by markocikos** [comment]
Hey @matethurzo ,

We are making an effort to remove jQuery from the entire portal, see https://issues.liferay.com/browse/LPS-83822. The staging and staging-related modules are your domain, so I'm sending PR to you for a final ok.

**Comment by matethurzo** [comment]
@markocikos ok we'll need to see if tests are passing

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:staging

**Comment by markocikos** [comment]
Hey @matethurzo,

I rebased to check for conflicts and force-pushed.

It seems the tests are failing on an unrelated module:
```
     [exec] Caching node_modules of project ':private:apps:portal-workflow:portal-workflow-metrics-web' in /root/.liferay/node-modules-cache/1347771788
     [exec] 
     [exec] > Task :private:apps:portal-workflow:portal-workflow-metrics-web:expandJSCompileDependencyComliferayfrontendjsweb300
     [exec] > Task :private:apps:portal-workflow:portal-workflow-metrics-web:expandJSCompileDependencies
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':private:apps:portal-workflow:portal-workflow-metrics-web:npmRunBuild'.
     [exec] > java.io.IOException: Process '[/opt/dev/projects/github/liferay-portal/build/node/bin/node, /opt/dev/projects/github/liferay-portal/build/node/lib/node_modules/npm/bin/npm-cli.js, --production, false, --registry, http://mirrors.lax.liferay.com:4873, --loglevel, warn, --progress, true, run, build]' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':private:apps:portal-workflow:portal-workflow-metrics-web:npmRunBuild'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59
```

Please review the code.

Thank you!

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70895. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
