### PR TITLE
LPS-89175 content processing order changed

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
@matethurzo this PR contains commits from https://github.com/matethurzo/liferay-portal/pull/2412
Please, review that one first.
Thx

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72621. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/bcb205c7bc06~3...bcb205c7bc06) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
