### PR TITLE
LPS-75894

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-75894

### CODE REVIEW

**Comment by giros** [comment]
ci:reopen

**Comment by giros** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53661. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
