### PR TITLE
LPS-55015

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by danielkocsis** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26405. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/05102cd~2...05102cd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
