### PR TITLE
LPS-84492 staging-variation-selector css class fixed to display the Page Variation and Site Page Variations select correctly

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
ci:stop

**Comment by zoltancsaszi** [comment]
ci:test:staging

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66042. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
