### PR TITLE
LPS-76046 Create WC portlet data handler tests before flipping to composition

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-76046

Related com-liferay-journal pr: https://github.com/matethurzo/com-liferay-journal/pull/6

cc @ZoltanCsaszi

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by giros** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54158. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/40a13e9b17e5~2...40a13e9b17e5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
