### PR TITLE
LPS-55833 Extract export import logic from portlet configuration portlet

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
CC: @ealonso

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26952. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3f4e9cd~1...3f4e9cd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
