### PR TITLE
LPS-75933 PortletDataHandlerTests - IGDisplayPortletDataHandlerTest fix

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53148. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/ef72579a5a8d~10...ef72579a5a8d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53169. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/0b48f71cc1b7~10...0b48f71cc1b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53274. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2135ef9f66a6~1...2135ef9f66a6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53305. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/b84caf0f8582~2...b84caf0f8582) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53339. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/f954e4c1353b~2...f954e4c1353b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
