### PR TITLE
LPS-63854 NPE is thrown when there is a reference from JournalArticle to a deleted layout

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by matethurzo** [comment]
Thanks I'll review it soon!

**Comment by jorgediaz-lr** [comment]
Rebase of https://github.com/matethurzo/liferay-portal/pull/1418

Seems there were some paths changes

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about the review of this pull request?

Thank you

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

I have rebased all my pulls to last master level.

My code is unchanged

**Comment by matethurzo** [comment]
Thanks, I'm reviewing it now.

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37680. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/b62da51~2...b62da51) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
