### PR TITLE
LPS-65895

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Information from Sherly

Import wiki with "Copy as new", will create a new wiki page, so needn't set uuid in serviceContext. The existingPage should always be null, so needn't fetch it.

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hi @sherlyliu, I think the logic is broken. If the setting is 'copy is new' than the page should be added as brand new, however if you check the local service validate method, WikiPageLocalServiceImpl:3212 if the title is being used it will fail.

Basically this change causes a problem in the following scenario:
- user publish a wiki page called 'Page 1'
- user publishes the same page 'Page 1' but with copy as new option
- the execution will reach WikiPageStagedModelDataHandler:248 where we pass the 'Page 1' title without any transformation.
- the publication fails because the local service validate method will check for the duplicate title.

Can you please check your solution given these information?

**Comment by sherlyliu** [comment]
Hi @matethurzo, I checked the code, and did some test about it, since when we import with "Copy as new", will create a new node. So the nodeId will be different per time. 
The validate method check title by 2 parameters, nodeId and title, so DuplicatePageException will not occur.

Thanks,
Sherly

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Hey @sherlyliu, Sorry my steps were incorrect, I wrote publish but what I actually meant was this:

- In a site create a wiki page called 'Page 1'
- Export the full site with all contents
- create a new site
- Import the LAR into the new site.
- Once more import the same LAR into the new site but the the copy as new option.
- The import fails because we already have the 'Page 1' in the target site.

I just tested it and it fails on the code line I wrote earlier.

**Pull request closed without merging**
