### PR TITLE
LPS-93112

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-93112

@danielkocsis 
@zoltancsaszi

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by giros** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70886. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
