### PR TITLE
LPS-53033

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by matethurzo** [comment]
Running test again to make sure everything is ok ci:retest

**Comment by matethurzo** [comment]
Hey,

Can you please investigate if the tests are failing due to the change or not?

Thanks,

Máté

**Comment by jonathanmccann** [comment]
@holatuwol

**Comment by holatuwol** [comment]
@matethurzo It's a NullPointerException in MBMessageLocalServiceImpl.notifyDiscussionSubscribers, which does not invoke any document library code updated by this change.

**Comment by matethurzo** [comment]
I'm going to check this soon.

Thanks,

Máté

**Comment by matethurzo** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
