### PR TITLE
pr-1388

### PR DESCRIPTION
**Pull request by kmaria**

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36643. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/28b33c2~1...28b33c2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
