### PR TITLE
LPS-92032 Export the AssetLinks if present

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70166. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
