### PR TITLE
LPS-87942 Create test for journal article's CT configuration

### PR DESCRIPTION
**Pull request by giros**

### CODE REVIEW

**Comment by giros** [comment]
@danielkocsis
@zoltancsaszi

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66858. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3b2fbed1cff7~2...3b2fbed1cff7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
