### PR TITLE
LPS-78957 . lexicon 2 upgrade

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Máté,

I do not like the change from <portlet:renderURL> to java generating the url, it could be solved with copyCurrentRenderParameters="false", however, I think that there are two bugs in portal which causes this bad behaviour, so I did not edit the code. I linked the LPSs into this LPS.

Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by peterborkuti** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57360. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57406. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/d0e3fd626c20~1...d0e3fd626c20) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
