### PR TITLE
LPS-82519 portlet staging option can be displayed when property ' staging.live.group.remote.staging.enabled' set to true

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
ci:retest

**Comment by zoltancsaszi** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62058. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
