### PR TITLE
LPS-63854 NPE is thrown when there is a reference from JournalArticle to a deleted layout

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @matethurzo

I have been doing some tests at master with a real database of a customer upgraded from 6.2 to 7.0 and this is one of the issues I have detected.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

I think failed tests are unrelated with my changes

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @jorgediaz-lr can you please rebase? It has a rebase error. Thanks!

**Pull request closed without merging**
