### PR TITLE
LPS-74083

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @matethurzo,

Please review this fix from @yuhai.

I am not sure what the intended behavior is in the case that you are exporting/importing a web content with a link to a page on the same site as the web content. As I see it, there could be two possibilities for the intended behavior:

1. The behavior in this fix, where if the link is a link of the same site it is exported from, we assume that the imported link should go to the site that you linked to.
2. The link is treated as an absolute link, and will always link to the site that it originally linked to when it was exported.

I am not sure which of these cases is the intended behavior, and I think an argument could be made for either one. Perhaps the (1) behavior could be used as the default, and then the (2) behavior could be used if we determine that (1) behavior would lead to an invalid link on importing? Let me know what you think.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
The test failure `DefaultExportImportContentProcessorTest.testExportLayoutReferencesWithContext` appears to be related.

**Comment by yuhai** [comment]
I tested this pr in my local. 

DefaultExportImportContentProcessorTest.testExportLayoutReferencesWithContext works well.

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi @matethurzo,

If you want to check the fix explanation, please refer to https://github.com/hhuijser/liferay-portal/pull/2968#issue-250579679

Regards,
Hai

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@mbowerman @yuhai so in case the link is pointing to the same site, it should be updated if we can update it during the process.

if it's pointing to any external site meaning non-liferay, or if it points to a site that is liferay, but outside of the site we are currently publishing or exporting, it should leave it like that.

is this fix working according to these rules?

**Comment by yuhai** [comment]
Hi @matethurzo,

Yes, I think so. The fix followed with the rules. 

**Case1**: export link page doesn't belong to current export site, keep same after import. 
DXP site: exist one page "testPage", http://localhost:8080/web/**guest**/testPage
Export Site1: create one web content, its content includes:
<a href="http://localhost:8080/web/**guest**/testPage">invoke testPage from DXP site</a>
Import Target Site2: It will keep **guest** site
<a href="http://localhost:8080/web/**guest**/testPage">invoke testPage from DXP site</a>

**Case2**: export link page belongs to current export site.
Export Site1: exist one layout:testPage, create one web content, its content includes:
<a href="http://localhost:8080/web/**site1**/testpage">link</a>
Import Target Site2: It will replace site1 with **site2**,  after import: 
<a href="http://localhost:8080/web/**site2**/testpage">link</a>

**Case3**: export link page is not liferay site, keep same after import. 
Export Site1: create one web content, its content includes:
<a href="http://www.google.com">link</a>
Import Target Site2: keep same
<a href="http://www.google.com">link</a>

Please kindly let me know if my understanding is not right.

Regards,
Hai

**Comment by yuhai** [comment]
Hi @matethurzo ,

I find I made a type mistake regarding the third commit message "LPS-74803 Fix test", actually, it should be LPS-74083. Sorry for this. If the fix looks good for you, could you please help change the commit info?

Regards,
Hai

**Comment by mbowerman** [comment]
Hey @materthurzo,

I was thinking about this fix a little more, and I was thinking that maybe for replaceExportHostname, we should not parse URLs that are going to a different group at all, unless maybe if it's a parent group or a global group. Since there is no guarantee that the group will exist in the destination site, do you think we should just leave the absolute link?

**Comment by yuhai** [comment]
Hi @matethurzo 

Since the issue came from EE customer, could you please review this when you have free time?

Regards,
Hai

**Comment by matethurzo** [comment]
hey guys,

as i wrote in the email this seems to be not a bug on master.

can you please verify?

thanks

**Comment by yuhai** [comment]
Hi @matethurzo ,

I still can reproduce the issue on the latest master. Please refer to the description from https://issues.liferay.com/browse/LPS-74083?focusedCommentId=1107465&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1107465

Could you please reopen the PR? 

In addition, the fix is for Case1 which I mentioned from https://github.com/matethurzo/liferay-portal/pull/1719#issuecomment-324521588.

Regards,
Hai

**Comment by matethurzo** [comment]
re-tested and it is an issue on master, the link is not correct after the import.

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51658. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/a940ec498dfd~3...a940ec498dfd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51659. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2dbe097a652b~3...2dbe097a652b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51681. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/fe507426f65b~4...fe507426f65b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51682. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/5980ce5cd8a1~4...5980ce5cd8a1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi @matethurzo 

Thanks for working on it.

I check your changes and I have one concern regarding the behavior:

1. Create one stagingSite. Enable this site local staging.
2. In staging site: the web content link own site page(stagingSite: page1).
3. In live site: the web content link should link live site page (liveSite: page1) after publish to live.

After the change, in live site, it looks like the web content link to stagingSite page after publish to live.

Sorry I can't test the issue because "ant all" executes failed. After ant all successful, I will let you know my test result.

Regards,
Hai

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51739. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/d20be09c981d~5...d20be09c981d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi @matethurzo 

I finish my test. I find the below behavior will be changed with the changes.

**Case1**: export link page belongs to current export site.
In same database.
Export Site1: create one layout:testPage and create one web content in Site1, its content includes:
<a href="http://localhost:8080/web/site1/testpage">link</a>
Import Target Site2: It will keep this link after import:
<a href="http://localhost:8080/web/site1/testpage">link</a>

**Case2**: staging environment.
1. Create one stagingSite. Enable this site local staging.
2. In staging site: create one page: page1, add one web content and its link to (stagingSite: page1).
<a href="http://localhost:8080/web/stagingSite-staging/page1">link</a>
3. Publish to live. In live site: the web content link should be live site page (liveSite: page1) after publish to live. Actually, the link still be 
<a href="http://localhost:8080/web/stagingSite-staging/page1">link</a>

Actually, the above two cases should be same case. When the link points at the current site, after import, they should use targetImport site, is it right? The fix behavior will be different from before fix.

Could you please check this?

Regards,
Hai

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51777. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/4795693f0b86~5...4795693f0b86) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
