### PR TITLE
LPS-87498 Guest is able to download lar files

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @matethurzo,

This PR reverts some changes that granted unconditional VIEW access to LAR files, replacing that with permission checks. We did a similar fix for LPS-86716, but forgot to /cc you in the PR. Sorry!

We're not 100% sure we've got rid of all issues, so if you find any other case (or receive any PR doing something related to that) could you ping me or @robertoDiaz so that we can add the permission checks? We'd like to be aware of all security issues related to the use of PortletFileRepository.

Thanks!

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by arthurchan35** [comment]
@matethurzo 
cc @robertoDiaz 

Hi guys,
Just wonder any progress for this review? Our https://issues.liferay.com/browse/LPP-31889 has been open for a long time.

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
ci:test:relevant

**Pull request closed without merging**
