### PR TITLE
Lps 82680 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by akosthurzo** [comment]
ci:reopen

**Comment by akosthurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61104. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3b4c8b809232~2...3b4c8b809232) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
