### PR TITLE
LPS-79312

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-79312

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61873. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62052. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/b6e5a1ba3c3e~1...b6e5a1ba3c3e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62057. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/43c7cf8e33f6~2...43c7cf8e33f6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
