### PR TITLE
LPS-95420 | "Submit for Publication" doesn't disappear after clicking the submit button

### PR DESCRIPTION
**Pull request by markocikos**
Hi @matethurzo ,

Please review the code.

Thank you!

/cc @mateomustapic @danielkocsis

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hi @markocikos,

I checked the fix and the original solution was this: https://github.com/liferay/liferay-portal/commit/b5ea47ff16205b7c24e481ef1ff999d52adc60ca

And the new is this:
https://github.com/matethurzo/liferay-portal/pull/2613/commits/3fe259593440568180edc57ff55830bae3a50c0f

My problem is that this fix doesn't restore the original logic, with the rich tooltip message telling the user already have a submitted review request, but simply hides the submit button when there is a pending request. Isn't there any solution to reproduce the same end result without JQuery?

thanks,
Daniel

**Comment by markocikos** [comment]
Hey @danielkocsis ,

It is true, the fix does not restore original logic. We remove the original logic because the code within `<c:when>` would never do anything. More specifically, the code defines an event listener on an element with `.submit-link` class, but such an element will never appear in UI.

However, we made a mistake in removing the `<c:when>` as well, that is the case of this ticket. The correct solution is:
```
<c:when test="<%= workflowEnabled && !pendingLayoutRevisions.isEmpty() %>">
    // do nothing
</c:when>
```
That is equivalent to the original code. But, by removing the whole `<c:when>`, it went into `<c:otherwise>`, which is not nothing.

The solution in this PR implements above, just rearranged to simplify / reduce code.

/cc @mateomustapic

**Comment by markocikos** [comment]
@danielkocsis To clarify a bit on why the original code does nothing:
1. The event listener on `submit-link`  is defined under `<c:if test="<%= !hasWorkflowTask %>">`
1. The `<liferay-ui:icon>` with `submit-link` class is only displayed under `<c:if test="<%= hasWorkflowTask %>">`

We practice not changing jQuery to vanilla JS blindly, without testing the change. After we found this change impossible to test, we opted to remove the code. Unfortunately, we didn't remove it cleanly and caused this bug.

I still believe this is the correct approach.

If you disagree or think the change is too risky, we can revert to original and replace 1 to 1.

**Comment by danielkocsis** [comment]
Hi @markocikos,

thanks for the explanation! I think based on this info it can work for now. Could you please close the pr and send a new one to me with the corrected solution!

thank you!
Daniel

**Comment by markocikos** [comment]
@danielkocsis You wish to revert to original, with the blind replacement?

**Comment by markocikos** [comment]
@danielkocsis If you agree with my reasoning, that unused code should be removed, then this PR **is** the corrected solution.

**Comment by danielkocsis** [comment]
@markocikos yes, I agree with the explanation and the proposed fix. Please just send the very same aolution to me instead of Mate. Thanky!

**Comment by danielkocsis** [comment]
PR has been sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/73592

**Pull request closed without merging**
