### PR TITLE
Lps 76633 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by akosthurzo** [comment]
ci:reopen

**Comment by akosthurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pushed to Brian under different tickets in this story: https://issues.liferay.com/browse/LPS-76633

**Pull request closed without merging**
