### PR TITLE
LPS-54462

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by ssmith353** [comment]
ci:retest

**Comment by ssmith353** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26337. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/fcd02fc~2...fcd02fc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
