### PR TITLE
LPS-86383 default serverPort fallback added, sync rule,  cleanUp

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by zoltancsaszi** [comment]
In Arquillian, I couldn't mock StagingServiceHttp, nor TunnelUtil because they are normal static util classes. That's why I provided a default fallback port number to the remote test.

**Comment by zoltancsaszi** [comment]
ci:retest

**Comment by pyoo47** [comment]
Here's the actual failure:
```
validate-pull-request-branch:
     [exec] /opt/dev/projects/github/liferay-subrepo-tools/bin/git-lpush -b master -o 5eac708d1c60fbf8406d5822fcf7f50e94eb73ee -s 2b2b99d6060c0c45119e9841ff055230f3150ab4 -r liferay-portal -v
     [exec] master: Verifying.
     [exec] error: Illegal nested revert, i.e. revert of a revert.
     [exec] error: Illegal nested revert, i.e. revert of a revert.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20181211122423553
```

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
thanks @pyoo47!

**Pull request closed without merging**
