### PR TITLE
[Technical-Support] LPS-78127

### PR DESCRIPTION
**Pull request by yuhai**
Hi @matethurzo 

Hope you are well. 

Based on https://issues.liferay.com/browse/LPS-78127?focusedCommentId=1254817&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1254817, I send the fix to you to review.  Please refer to the explanation (current talk) from https://github.com/epgarcia/liferay-portal/pull/588#issue-171153090

cc @drewbrokke and @epgarcia 

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi @matethurzo 

Hope you are well.

Since the issue came from EE customer, could you please review it when you have free time?

Regards,
Hai

**Comment by moltam89** [comment]
Hi @yuhai ,

I was asked to look into this fix, and I'm not sure that this is the right approach.

As far as I can see, when we modify the settings for e.g. the Message Boards portlet, in the **_portletpreferences_** table there will be 2 new entries, one with _portletId_ _com_liferay_message_boards_web_portlet_MBAdminPortlet_ and the other with _portletId_ _com.liferay.message.boards_.

Do you know if there is a reason behind this behavior, or is it a bug?

E.g. if I put an Asset Publisher portlet to a page, when I open it's configuration, a new **_portletpreferences_** entry will be created, then when I hit the save button, this entry is being updated, therefore the _onAfterUpdate_ runs properly.

On the other hand, when I open the Message Boards portlet's configuration, an entry will be created in the **_portletpreferences_** table, however, when I hit the save button, another entry will be generated.
Shouldn't we just update the first one, so the _onAfterUpdate_  could run correctly solving the current issue?

As far as I can see, right now we're just creating trash entries in the **_portletpreferences_** table which are not used.

Thanks,
Tamás

**Comment by yuhai** [comment]
Hi @moltam89 

Thanks for reviewing this.

> Do you know if there is a reason behind this behavior, or is it a bug?
I think they are expected behavior. Please refer to the below explanation.

**1**. Generate com_liferay_message_boards_web_portlet_MBAdminPortlet portletpreferences:
This is common logic when click portlet's configuration, PortletConfigurationPortlet.render() will be invoked. And it will check related portletpreferences data whether existed in portletpreferences table.

Case 1: put an wiki portlet (portletId: **com_liferay_wiki_web_portlet_WikiPortlet**) to a page. UpdateLayoutAction.storeAddContentPortletPreferences() will create related portletpreferences data.

Case 2: go to Content->Wiki (portletId=com_liferay_wiki_web_portlet_WikiAdminPortlet), this is admin portlet and only display view.jsp. Only when click portlet's configuration, its related portletpreferences data (portletId: **com_liferay_wiki_web_portlet_WikiAdminPortlet**) will be created.

2. Generate "com.liferay.wiki" portletpreferences
It only is created when click "save" button in the configuration page. Please refer to https://github.com/yuhai/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SettingsConfigurationAction.java#L124 ->https://github.com/yuhai/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SettingsConfigurationAction.java#L252-L269.
When save **com_liferay_wiki_web_portlet_WikiPortlet**, its serviceName is null and settingsScope="portletInstance". When save in **com_liferay_wiki_web_portlet_WikiAdminPortlet** configuration page, its serviceName="com.liferay.wiki" and settingsScope="group". Please refer to https://github.com/yuhai/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki_admin/configuration.jsp#L24-L25 and this configuration only be invoked when view the configuration page. **That is to say, serviceName="com.liferay.wiki" portletpreferences data only is created after click "Save button"** (Please also check https://github.com/yuhai/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SettingsConfigurationAction.java#L105-L107). For other modules, the logic is same. Please refer to https://github.com/yuhai/liferay-portal/blob/master/modules/apps/collaboration/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards_admin/configuration.jsp#L26-L27

Please let me know if you have further concerns.

Regards,
Hai

**Comment by moltam89** [comment]
Hi @yuhai ,

sorry, but I don't really understand this explanation.
For me it's not logical to create 2 portletpreferences entry when I save only 1 configuration.

Could you please explain it why 2 entries are created if only one of them is used?

Thanks,
Tamás

**Comment by yuhai** [comment]
Hi @moltam89,

As we know, they are not created together.

**For com_liferay_message_boards_web_portlet_MBAdminPortlet portletpreferences portletpreferences, it is created when click the configuration (access to the configuration page)**. This is common logic: PortletConfigurationPortlet.render() will be invoked. if its portletpreferences data doesn't exist, it will be created.

**For "com.liferay.wiki" portletpreferences, the issue only is related with this portletpreferences because it will be created when save configuration.**
Refer to the logic:
https://github.com/yuhai/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki_admin/configuration.jsp#L24-L25  ->
https://github.com/yuhai/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SettingsConfigurationAction.java#L105-L107  ->
https://github.com/yuhai/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SettingsConfigurationAction.java#L124 ->
https://github.com/yuhai/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SettingsConfigurationAction.java#L252-L261

This looks like expected design by saving the configuration, instead of saving "com_liferay_message_boards_web_portlet_MBAdminPortlet" portletpreferences.

In addition, when save the configuration, it also will use "com_liferay_message_boards_web_portlet_MBAdminPortlet" portletpreferences. Please refer to the 
 logic:
https://github.com/yuhai/liferay-portal/blob/master/modules/apps/web-experience/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/portlet/PortletConfigurationPortlet.java#L173 ->
https://github.com/yuhai/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/portletconfiguration/action/ActionUtil.java#L251-L252, if "com_liferay_message_boards_web_portlet_MBAdminPortlet" portletpreferences doesn't exist and it also will be created in the process of saving configuration.

Regards,
Hai

**Comment by moltam89** [comment]
Hi @yuhai ,

actually I was interested in the reasons behind this behavior, as it still seems fishy to me.
I opened an SME request to clarify if it's intentional or not, as actually the portletpreferences related problem is not really staging related, it's a general behavior.

Thanks,
Tamás

**Comment by yuhai** [comment]
Thanks, @moltam89

**Comment by matethurzo** [comment]
hey @yuhai I was talking to @moltam89 and I'd like to wait and see the result of the BPR ticket too.

Also I share Tamás' concern on if this is the right approach. We need to address the pending questions first to be able to make progress with this pull request.

**Comment by samuelkong** [comment]
@matethurzo I assume you mean SME ticket ticket since there's no BPR ticket for this ticket yet.

**Pull request closed without merging**
