### PR TITLE
LPS-72927 JournalArticleSMDHTest fetchFromParentSite TestCase added

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
please rebase and re-send. also there seem to be source formatting errors please fix them.

**Pull request closed without merging**
