### PR TITLE
LPS-74947

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @almonwork @dacousalr

**Comment by robertoDiaz** [comment]
Hi @matethurzo 

We have removed this logic because the solution is breaking some operations that customers usually do when using remote staging.

Since the error that we wanted to fix in the original ticket (LPS-63724), following the documentation, could be consider a wrong use of the product, and the solution itself is causing problems to customers (see LPS-64548 and the current LPS), we prefer to rollback, at least by the moment.

Thanks!!

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @robertoDiaz @almonwork @dacousalr,

the code change looks okay, and we discussed that this should infer any problems, but I'd be more comfortable if we could find a way to validate still if it's the same group.

currently it's only using the uuid as a base for validation, this is why a cloned DB is not working. we could however improve the validation if we could detect the if the host is the same. If we could validate with the host we could safely validate the same group still while allowing cloned DB usage too

**Comment by robertoDiaz** [comment]
Hey @matethurzo,

Could we move this code forward in order to fix the customer issues until we found the final solution?

Current situation is forcing us to create a lot of hotfixes because customers are using cloned DDBB, and we have to rebase this changes in almost all the fixpacks.

Thanks!!

**Comment by matethurzo** [comment]
@robertoDiaz I'll push it forward, but we'll need to find a more sophisticated solution

**Comment by robertoDiaz** [comment]
Hey @matethurzo 

Thank you!!

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52556. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@robertodiaz pushed to Brian. @almonwork are you guys going to have bandwidth for the more sophisticated solution? or should we handle it?

**Comment by almonwork** [comment]
Hi @matethurzo ,

Sorry for the late reply. We were trying to find solutions in the past (locks, comparisons, etc.) and we did not come to any good solution. I guess this means there is no easy alternative.

In the end, we are preventing a very rare situation. Woudn't it be enough just documenting it?

Regards

**Pull request closed without merging**
