### PR TITLE
[TECHNICAL-SUPPORT] LPS-76690 The 'Link' function in web contents cannot be published with non default locales.

### PR DESCRIPTION
**Pull request by moltam89**
Hi Máté,

this is a small fix to properly validate references to layouts with non default locales as well.

Vendel used the same method which works correctly during the export process, see [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/content/processor/LayoutReferencesExportImportContentProcessor.java#L462).

Thanks,
Tamás

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54536. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
