### PR TITLE
LPS-87688 PanelApps can be added to ProductNavigation User panel

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2307. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/aea77fda457e~5...aea77fda457e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65571. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/ecdbcdae30da~9...ecdbcdae30da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65577. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/259213ddaa39~10...259213ddaa39) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
