### PR TITLE
LPS-78512 lexicon 2 for navigation + toolbar (addbutton) in publishing export and import

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Máté,

Here is @palius pull, Marcsi has seen it.
(Now I could fix the build.gradle.)

Thank you
Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by peterborkuti** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56537. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2845ce0e30f3~1...2845ce0e30f3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
