### PR TITLE
[TECHNICAL SUPPORT] LPS-84201

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-84201

In order to maintain site scope configuration in Asset Publisher, now, for Remote Staging we stored a mapping information of groupIds (see  [LPS-60568](https://issues.liferay.com/browse/LPS-60568))

But in case of doing a export/import using LAR files, scope info is lost unless a site with same groupId exists.

In SME request [LPP-30970](https://issues.liferay.com/browse/LPP-30970) I agreed with @moltam89 to use groupKey as a fallback of groupId, so in case of not existing the exported groupId, we will search a group with the same name.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Do you have any update about this pull request?

I would like to send this fix to the customer as soon as possible.

/cc @moltam89 as SME of Staging functionality, can you talk product team in order to unblock this pull request review?

Thank you

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo

Do you have any update about this pull request?

Thank you,
Jorge

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62481. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/c81f1e29ff7c~2...c81f1e29ff7c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
