### PR TITLE
LPS-70830 add getPermissions to test

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
