### PR TITLE
LPS-76668

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-76668

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60221. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
