### PR TITLE
[TECHNICAL-SUPPORT] LPS-84784

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-84784
> https://issues.liferay.com/browse/LPP-31297
> 
> **Problem**: Publishing a page created by a Global Template in 7.1/master can be Imported into a separate bundle, but then when that page it was imported to is Exported, the export fails. This is because the Global Template the page was based on was never imported.
> 
> **Solution**: Based on Tamas' suggestion [here](https://issues.liferay.com/browse/LPP-31343?focusedCommentId=1523738&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1523738). During the import we will search for the layoutPrototype if it was preloaded and connect the page based on the Global Template to what is found. This was already happening during the validation process [here](https://github.com/joshuacords/liferay-portal/blob/8da25429f78276cf8ff934541f8a7b427a2e280d/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/LayoutImportController.java#L1377-L1404).

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62928. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/30a1950a5e76~1...30a1950a5e76) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
