### PR TITLE
[TECHNICAL-SUPPORT] LPS-81981

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @wanderlast:

> LPS: https://issues.liferay.com/browse/LPS-81981
> LPP: https://issues.liferay.com/browse/LPP-30210 (the relevant breakdown of this issue is here though)
> 
> This issue is focused on remote staging over three separate instances--specifically trying to publish to a third instance/site that is not a part of the initial staging/remote live pair. In the current code, we get the remoteGroupID from our typeSettings which is the value saved when staging is first setup. Therefore this remoteGroupID is always equivalent to the initial remote live groupID even if our publication is setup to publish to another site. This causes issues for two reasons:
> 
> 1. The remoteGroupID isn't necessarily the one we're publishing to, so verifying it exists is pointless.
> 2. The remoteGroupID may not exist on the portal instance that we're publishing to, even if the site we wish to publish does, causing an exception and causing the publish attempt to fail.
> The code currently checks for a specific configuration and grabs all other remote options from that configuration (e.g. the port, connection path, etc). The fix therefore changes the remoteGroupID to the targetGroupID from that configuration if it exists since it is equivalent to the site we actually will publish to.
> 
> Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @matethurzo,

Would it be possible to have an ETA for when you might have a chance to look at this PR? Thank you!

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60226. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
