### PR TITLE
LPS-73188 Error log when create Site based on Site Template and merge-fail-count greater than PropsValues.LAYOUT_SET_PROTOTYPE_MERGE_FAIL_THRESHOLD

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-73188

Hi @matethurzo,

This change only affect when a user try to create a site based on a site template, that's why we add this error log in this class. We didn't add this implementation over this warning
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/sites/util/SitesImpl.java#L1078-L1095 
to avoid writing an error trace every time an user visit a site with this merge-fail-count in his LayoutSet (this error is writing for each user visiting this site and for each page to show in navigation menu, so could affect server performance and the amount of log traces). 

Thanks!

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey @JosemariaMunoz the primary purpose of the the method _checkTraceLayoutSetMergeable is to check if a fail has occured right? if there was a fail then it will log the message

**Comment by JosemariaMunoz** [comment]
Hey @matethurzo, 

The primary purpose of the method _checkTraceLayoutSetMergeable is show an error message when an user try to create a site based on a site template and the LayoutSet has a "merge-fail-count" settings (something happens in past executions).

In this case, the process create a new Site but don't try to propagate Site Template Pages to new Site. This behavior is correct but it doesn't show any error message in logs.

In this way, we need an error trace in order to know why our new Site didn't propagate Site Template Pages.

This trace is on account of a LESA customer ticket that it takes so much time finding out why new Sites didn't propagate Site Template Pages.

Please let me know if you need more clarification about this issue.

Thanks!

**Comment by matethurzo** [comment]
hey @JosemariaMunoz one more question, basically we want to report after the merge failed?

the naming suggests that we are checking if it can be merged before we want to but we are actually checking after the merge

**Comment by JosemariaMunoz** [comment]
Hey @matethurzo,
Yes we want to report a "trace" from this "check" after merge failed, but it's only for trace this error in logs. 
There is no problem to change it if you think it would be better other name.

**Comment by JosemariaMunoz** [comment]
Hi @matethurzo,
Did you have time to review my last comment?
Please let me know if you need more information.
Thanks!

**Comment by JosemariaMunoz** [comment]
Hey @matethurzo, 
Do you have any update? Please, this implementation will help to find out those errors that have relation to Site Templates propagation. Not only for our Support but for customers that will see this trace in log files.
Thanks!

**Comment by almonwork** [comment]
Hi @matethurzo ,

We know this is not superurgent, as no customer is waiting for it. But this is one of those cases when little changes make a big difference as debugging will be much easier and support will be able to diagnose more effectively and with less burden for developers.

Could you please take a look?

Regards

**Comment by JosemariaMunoz** [comment]
/cc @almonwork 

Hi @matethurzo,

Did you have time to review this issue?

Thanks!

**Comment by JosemariaMunoz** [comment]
After so much time we close this PR.
It is seems that now we can obtain same logs using WARN level over 'com.liferay.portlet.sites.util.SitesImpl'

**Pull request closed without merging**
