### PR TITLE
LPS-67621

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
@ling-alan-huang @hhuijser from a code perspective this looks good but I need verification from the UX team if this is a correct fix or not. once they verify I'll push it forward

**Comment by matethurzo** [comment]
@ling-alan-huang @hhuijser I've followed up with the UX team on this I'll be adjusting the change according to that and I'll send it to Brian

**Comment by ling-alan-huang** [comment]
@matethurzo Thanks:)

**Comment by ling-alan-huang** [comment]
@matethurzo Thanks.

**Pull request closed without merging**
