### PR TITLE
Add getStagedModel() method to StagedModelRepository

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57876. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/0f85a12c8afe~2...0f85a12c8afe) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
