### PR TITLE
LPS-54100

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by matethurzo** [comment]
Hey guys,

I wasn't able to reproduce this issue, because there are other problems on latest master, following the steps in the ticket. Have you been able to reproduce this lately there?
I want to test and investigate this before merging it to master.

Thanks,

Máté

**Comment by zxdgoal** [comment]
Hey @matethurzo

I am trying to fixing LPS-54678 now. 

But I am a bit busy with some LPPs. 

Can you hold on this pr? 

When LPS-54678 is fixed, I will leave a comment on this pr. 

Thanks
John

**Comment by matethurzo** [comment]
Sure, I leave this open, please let me know when you have time.

Thx

**Comment by zxdgoal** [comment]
Hey @matethurzo 

It seems that Daniel's pr https://github.com/matethurzo/liferay-portal/commit/cc4360bda3d304828613ce66b038fef60357b482 fixed my issues.

```
if (stagedModelDataHandler == null) {
	return;
}
```

We cannot ``stagedModelDataHandler`` for ``Image`` class. Simply return.

You can close this pr.

Many thanks
John

**Comment by matethurzo** [comment]
Thanks!

Closing.

**Pull request closed without merging**
