### PR TITLE
LPS-74463 Button for changing between public and private pages is not working for publish templates

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Máté,

Could you please review it? I modified the taglib a lot. It is used by export template also, but I did not find any other place in the portal which uses this config_header tag.

Thank you in advance
Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:open

**Comment by peterborkuti** [comment]
ci:reopen

**Comment by peterborkuti** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51782. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
