### PR TITLE
LPS-82539 publishFolder action fix

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60996. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/fcf87456713e~2...fcf87456713e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61000. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/2683fba650e1~3...2683fba650e1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61002. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/045e73c1c2e4~3...045e73c1c2e4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61006. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/d5d9121f9e1a~4...d5d9121f9e1a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61035. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/0e42e1ad89ac~5...0e42e1ad89ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
