### PR TITLE
LPS-61648 - None version of a web content article is exported if the latest version is draft and version history flag is unchecked

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi Máté,

Review it please. Details are on the LPS.
Thank you in advance.

Regards,

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:retest

**Comment by antonio-ortega** [comment]
Hi Máté,

Could you review it? Thanks.

Regards,

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34457. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3d0da1b~1...3d0da1b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
