### PR TITLE
LPS-83326 JournalFolder import restrictionType fix

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zoltancsaszi** [comment]
ci:test

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61670. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/faea7f48f84c~9...faea7f48f84c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61672. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3c460c6f266d~10...3c460c6f266d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
