### PR TITLE
[TECHNICAL-SUPPORT] LPS-92285 Implement UserGroupStagedModelDataHandler doImportMissingReference

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @moltam89 and @matethurzo , 
I've done some further testing on 7.1.x using Audience Targeting, and when using Remote Staging the import will be "Successful" but it will have this warning in the publication details "Unable to execute process ([{"size":1,"type":"User Segment Rule","info":"The original User Group does not exist in the current environment."}])". The User Segment will be imported, but the User Group will not be linked to it (if the User Group was not already available for the importing site). I'm not sure if the Import should be failing or not in this case. And if it is supposed to fail, I don't know where it should fail from.

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70158. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by moltam89** [comment]
Hi Joshua,

This looks the expected behavior for me, however this is actually an application specific question.

Checking the [code ](https://github.com/liferay/liferay-apps-content-targeting-ee/blob/f8901f8d42372bd3e9de26907eb585cae6cd6e4b/rule/rule-user-group-member/src/main/java/com/liferay/content/targeting/rule/user/group/member/internal/model/UserGroupMemberRule.java#L76-L101) you linked me on the previous PR, I can see that the reference type is "REFERENCE_TYPE_WEAK".

If we would want the import to fail, we had to change the reference type to "REFERENCE_TYPE_DEPENDENCY".

Best,
Tamás

**Pull request closed without merging**
