### PR TITLE
LPS-58650

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

Seems failed tests (PortalLogAssertorTest.testScanXmlLog) are unrelated to my changes

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @matethurzo 

I have to send a hotfix to a customer in order to solve following issues:
*LPS-58650, LPS-58632, LPS-58629 and LPS-58631*

But before sending it, I would like to have a review of my solutions, to avoid future problems.
Can you have a look to the related pull requests?
  * **LPS-58650:** https://github.com/matethurzo/liferay-portal/pull/1182
  * **LPS-58632:** https://github.com/matethurzo/liferay-portal/pull/1187
  * **LPS-58629:** https://github.com/matethurzo/liferay-portal-ee/pull/164 (only 6.2.x)
  * **LPS-58631:** https://github.com/matethurzo/liferay-portal/pull/1189

Thank you

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30876. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
