### PR TITLE
LPS-83937 Use the right redirectURL from portletRequest.

### PR DESCRIPTION
**Pull request by yuhai**
Hi @matethurzo 

Hope you are well. 

I'm sending the PR for your review. Do let me know if I should send to someone else please.

The root issue is the redirectURL is not right. For the previous method, it will use generated redirectURL and this won't include some params (saveCallback, className.. in https://github.com/liferay/liferay-portal/blob/master/modules/apps/mobile-device-rules/mobile-device-rules-web/src/main/resources/META-INF/resources/edit_rule_group_instance_priorities.jsp).

The fix is using the redirectURL of portletRequest (Please refer to https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/bridges/mvc/BaseMVCActionCommand.java#L216), it will include necessary params. In addition, we only define one actionURL "/mobile_device_rules/edit_rule_group_instance" in this jsp (https://github.com/liferay/liferay-portal/blob/master/modules/apps/mobile-device-rules/mobile-device-rules-web/src/main/resources/META-INF/resources/edit_rule_group_instance_priorities.jsp#L32-L34), so we can get redirectURL from portletRequest based the fix.

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62931. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
