### PR TITLE
Lps 76847 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55128. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/6c4cbd4da567~1...6c4cbd4da567) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55251. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/bb35eb67e010~2...bb35eb67e010) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55374. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/bf540462adad~2...bf540462adad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
