### PR TITLE
Lps 59712

### PR DESCRIPTION
**Pull request by arbetts**
@matethurzo 

i broke up LPS-54744 into parts and this one relates mostly to staging... let me know if i should send it somewhere else.

the next pull creates a backgroundTaskDisplay object and i'll replace the staging specific logic in the taglib with that in order to make it reusable outside of staging

 ... small steps this time :)

### CODE REVIEW

**Comment by arbetts** [comment]
i ran into a few UI issues, but i tested before and after my commits and they were the same ... i assume that the UI is still fluctuating

**Comment by arbetts** [comment]
https://github.com/matethurzo/liferay-portal/pull/1222

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/497. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
