### PR TITLE
LPS-88848

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-88848

@danielkocsis
@zoltancsaszi

### CODE REVIEW

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by giros** [comment]
ci:test:sf

**Comment by giros** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66675. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/df6332a64bf2~2...df6332a64bf2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/693. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/df6332a64bf2~2...df6332a64bf2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
