### PR TITLE
[TECHNICAL-SUPPORT] LPS-79312

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @wanderlast

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
hey guys,

I'm not sure if this is a proper solution. hard coding a certain value or skip based on that usually seems not to be the perfect way to do something.

can you provide me more information on specifically where the two portlets are listed in the DataSiteLevelPortlets? The two portlets share the same data handler and I would think that the admin and the normal portlet should not have last publish dates each. please send me more tech details on how is this happening, and I can provide you more guidance.

@wanderlast @jonathanmccann

**Comment by wanderlast** [comment]
Hi @matethurzo,

Thanks for looking at this! The two portlets are listed as rank 90 and therefore appear [second and third in the DataSiteLevelPortlets](https://imgur.com/a/tYtwm), behind the rank 80 SiteTeamsPortlet. Both portlets have a LastPublishDate which can be seen by looking at their portletpreferences. DLAdminPortlet has multiple instances in portletpreferences due to the preferences being linked to the ownerID, since DLAdminPortlet has: "com.liferay.portlet.preferences-unique-per-layout=false". DLPortlet does not have this setting and therefore shares its preferences and last publish date among all staged sites.

As can be seen in the screenshots linked, either DLPortlet or DLAdminPortlet can be added first by the DataSiteLevelPortlets--I was unfortunately unable to trace the exact reason why the portlets are loaded in different orders. I _was_ able to replicate DLPortlet coming first (and therefore the bug) in an SP6 bundle patched to DE-40, but have been continuously unable to replicate it in Master or Branch. The CSE has been able to replicate it in both Master and Branch. However, either way, whichever is added first to DataSiteLevelPortlets is used by the simple version of the publishing summary. Since they share DataPortletHandlers, whichever portlet comes second is skipped since the data portlet handler is added to a list of previously used data handler class names--assumedly so that you don't end up with two instances of Documents & Media in the summary. I tried changing the DLAdminPortlet's OSGI rank but this caused additional issues. The issue _could_ be fixed by setting DLPortlet "com.liferay.portlet.preferences-unique-per-layout=false", but other similar portlets (e.g. WikiPortlet) do not appear to have the same issues and do not have that setting.

If you have any other questions, please let me know. Thanks!

**Comment by moltam89** [comment]
Hi @wanderlast ,

I took a quick look at this pull request and my first impression is that it's not only a Document Library issue, but a general one.
If I understand it correctly, we process the portlets which share the same PortletDataHandler in a random order and whenever the instanceable portlet comes before the Admin portlet, there is a high chance that something will go wrong.

This fix is for Document Library, but as you mentioned the problem is not reproducible in Master currently, as the portlets are coming in the right order.
On the other hand, there are other apps where we have Admin portlets, I could reproduce the problem with Bookmarks and Blogs. (I had to enable staging for them).

Could you please test the issue with Bookmarks/Blogs or any other apps where we have Admin portlets?

If I didn't miss something and this issue is reproducible elsewhere as well, then this fix cannot be merged to master, as we'll need a general solution.
Also, as Máté said it in his comment, hardcoding PortletKeys to general staging logic is usually not a good idea in the OSGI world.
Staging relies on the Document Library API currently because of how LARs are stored, but we couldn't add a new dependency e.g. for Bookmarks to fix this issue, as that would mean that Staging couldn't work without the Bookmarks app.

Thanks,
Tamás

**Comment by wanderlast** [comment]
Hi @moltam89,

Thank you so much for looking at this! A minor note: it is reproducible in master, but not consistently. The CSE on this ticket was able to reproduce it in master consistently, but I have not been able to reproduce it on my own system with identical portal settings. I I was not able to reproduce with Blogs, Bookmarks or Wiki personally, but this may be due to whatever is making it not reproducible for me in DL on master. Do you have or Máté any suggestions or advice on what may be a better avenue for a general fix? I've attempted to manipulate OSGI rank as my first attempt at a fix, but don't believe it will work in this case.

**Pull request closed without merging**
