### PR TITLE
[TECHNICAL-SUPPORT] LPS-76228

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @wanderlast

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Tests passing here - https://github.com/ChrisKian/liferay-portal/pull/26#issuecomment-367563625

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by moltam89** [comment]
Hi @wanderlast ,

I think this solution is a little bit too complicated and I'm note sure that it works correctly in all the cases.
E.g. if the first layout is "wrong", if I understand it correctly we will populate the layouts map anyways.

I'd suggest not to use the _fetchMissingReference_ method, which looks through all the groups unnecessarily, we could just grab the layout from the actual import group, which can be determined by portletDataContext.getGroupId().

 Also, if I remember correctly, by portletDataContext.isPrivateLayout() we can figure it out whether we are importing to a public or private layoutSet.

Thanks,
Tamás

**Comment by wanderlast** [comment]
Hi @moltam89 ,

Thanks for looking at this again! I was previously attempting to follow your suggestions on the [previous PR here](https://github.com/matethurzo/liferay-portal-ee/pull/222#issuecomment-360521820), but I might be misunderstanding what you suggested me to do. I'm afraid I don't understand what you mean to not use the fetchMissingReference method. The linked layout is treated as a 'missing reference' in the LAR file and therefore correctly calls to import the missing reference as far as I'm aware. The error is that it doesn't recognize that the layout it's calling as a missing reference should not be overwriting the actual layout since they share layoutIds. Are you saying that I should alter it so that it is not called at all?

I'm not sure  understand what you're referring to for the public/private layoutset's as well. Is that simply to refine the logic present? Thanks!

**Comment by moltam89** [comment]
Hi @wanderlast ,

I sent you a pull request and tried to explain what I meant using the commit messages.
https://github.com/wanderlast/liferay-portal/pull/8

Could you please test if this solves the original issue?

Please let me know if you have any questions.

Thanks,
Tamás

**Pull request closed without merging**
