### PR TITLE
LPS-60530

### PR DESCRIPTION
**Pull request by LeventeHudak**

### CODE REVIEW

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32668. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/kmaria/liferay-portal/pull/8. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
