### PR TITLE
LPS-57736

### PR DESCRIPTION
**Pull request by LeventeHudak**

### CODE REVIEW

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by LeventeHudak** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29236. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/b25a2fe~5...b25a2fe) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
