### PR TITLE
[TECHNICAL-SUPPORT] LPS-74024

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @Alec-Shay

Notes from Alec:

> Relevant tickets:
> 
> https://issues.liferay.com/browse/LPS-74024
> https://issues.liferay.com/browse/LPP-28136
> https://issues.liferay.com/browse/PTR-83
> 
> This change improves the explanation given when the "Mirror with overwriting" import strategy is not available for a given portlet. The current implementation simply reads "Not Supported," but this is unhelpful and confusing for users.
> 
> There was a long conversation on [PTR-83](https://issues.liferay.com/browse/PTR-83) about the proper way to handle this, which culminated in the decision to remove the option altogether in 7.1, and update the help message in 7.0. However, as per [this comment on LPP-28136](https://issues.liferay.com/browse/LPP-28136?focusedCommentId=1213462&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1213462), it seems that there is not enough bandwidth to be able to push through the removal of this feature from 7.1, so to be able to get this fix in for 7.0, we must first commit it to master.
> 
> Due to problems related to [LPS-76221](https://issues.liferay.com/browse/LPS-76221), we have not been able to generate new language keys -- but as per [this comment on LRSUPPORT-19936](https://issues.liferay.com/browse/LRSUPPORT-19936?focusedCommentId=1218406&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1218406), for now we should be able to manually add the language keys to the languages needed (for a customer's issue). Thus, since a `gradlew buildLang` will not work for now, the message was simply manually added to Language_en.properties.
> 
> Please let me know of any questions or concerns about this. Thank you.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
pushed to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/55156

**Pull request closed without merging**
