### PR TITLE
[TS] LPS-74827

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
Hi @matethurzo,

The test error should be not related with the PR. 
Same error also occured in
https://github.com/brianchandotcom/liferay-portal/pull/51893
https://github.com/brianchandotcom/liferay-portal/pull/51894

Regards,
Hai

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/arboliveira/liferay-portal/pull/342. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
