### PR TITLE
LPS-96578 getProcess method will return a specific process with the given processId

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:change-tracking

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74813. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/e396a4e6bc35~3...e396a4e6bc35) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
