### PR TITLE
Lps 81693 master

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59386. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/ced6fb98f2bf~1...ced6fb98f2bf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
