### PR TITLE
[TECHNICAL SUPPORT] LPS-88571

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-88571

Regression caused by [LPS-54392](https://issues.liferay.com/browse/LPS-54392), in case groupId doesn't exists a NPE is thrown.

**Important:** There is a special case only for DLFileEntryType object with key=BASIC-DOCUMENT with groupId=0 because is precreate during Liferay startup with _fileEntryTypeId=0, companyId=0 and groupId=0_
So only in DLFileEntryTypeStagedModelDataHandler is necessary to handle that special case.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66669. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
