### PR TITLE
LPS-72545

### PR DESCRIPTION
**Pull request by akosthurzo**

### CODE REVIEW

**Comment by akosthurzo** [comment]
ci:test

**Comment by akosthurzo** [comment]
ci:reopen

**Comment by akosthurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/2214. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/290de23c6ed6~4...290de23c6ed6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matethurzo** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61790. [See changes here.](https://github.com/matethurzo/liferay-portal/compare/3ed40f4c7e74~6...3ed40f4c7e74) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
